// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

// Referenced classes of package com.paypal.android.sdk:
//            j, cs

public final class r
    implements j
{

    private static Map a = new HashMap();
    private static Map b = new HashMap();
    private static Map c = new HashMap();

    public r()
    {
        a.put(cs.a, "Aceptar y pagar");
        a.put(cs.b, "y otro");
        a.put(cs.c, "Autenticando");
        a.put(cs.d, "Atr\341s");
        a.put(cs.e, "Garant\355a");
        a.put(cs.f, "Cancelar");
        a.put(cs.g, "American Express");
        a.put(cs.h, "Carta Aura");
        a.put(cs.i, "Carte Aurore");
        a.put(cs.j, "Carta Prepagata PayPal");
        a.put(cs.k, "Carte Bancaire");
        a.put(cs.l, "Cofinoga");
        a.put(cs.m, "Delta");
        a.put(cs.n, "Discover");
        a.put(cs.o, "Electron");
        a.put(cs.p, "JCB");
        a.put(cs.q, "Maestro");
        a.put(cs.r, "MasterCard");
        a.put(cs.s, "Postepay");
        a.put(cs.t, "4 \351toiles");
        a.put(cs.u, "Tarjeta Aurora");
        a.put(cs.v, "Visa");
        a.put(cs.w, "Cambiar forma de pago");
        a.put(cs.x, "Cheques");
        a.put(cs.y, "Comprobando el dispositivo\u2026");
        a.put(cs.z, "Borrar los datos de la tarjeta");
        a.put(cs.A, "Confirmar");
        a.put(cs.B, "\277Seguro que desea borrar los datos de su tarjeta?");
        a.put(cs.C, "Cargar en tarjeta");
        a.put(cs.D, "\277Est\341 seguro que desea cerrar la sesi\363n de PayPal?");
        a.put(cs.E, "Pagar");
        a.put(cs.F, "Aceptar");
        a.put(cs.G, "Fecha de apertura de la cuenta");
        a.put(cs.H, "Estado de la cuenta");
        a.put(cs.I, "Tipo de cuenta");
        a.put(cs.J, "Direcci\363n");
        a.put(cs.K, "Rango de edad");
        a.put(cs.L, "Fecha de nacimiento");
        a.put(cs.M, "Direcci\363n de correo electr\363nico");
        a.put(cs.N, "Nombre completo");
        a.put(cs.O, "Sexo");
        a.put(cs.P, "Idioma");
        a.put(cs.Q, "Configuraci\363n regional");
        a.put(cs.R, "Tel\351fono");
        a.put(cs.S, "Zona horaria");
        a.put(cs.T, "Compartir lo siguiente: %s.");
        a.put(cs.U, "%s le solicita que usted:");
        a.put(cs.V, "Comparta las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        a.put(cs.W, "Active la visualizaci\363n de sus opciones de pago para que usted pueda elegir.");
        a.put(cs.X, "<a href='%1$s'>Autorizar cargos</a> correspondientes a futuras compras en %2$s pagadas con PayPal. Le instruye a PayPal de pagar todos los importes solicitados por %3$s.");
        a.put(cs.Y, "Le permita agregar y administrar su tarjeta de lealtad en su cartera de PayPal.");
        a.put(cs.Z, "Acepte la <a href='%2$s'>Pol\355tica de privacidad</a> y las <a href='%3$s'>Condiciones de uso</a> de %1$s.");
        a.put(cs.aa, "Le permita <a href='%1$s'>solicitar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        a.put(cs.ab, "Le permita <a href='%1$s'>enviar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        a.put(cs.ac, "Permiso");
        a.put(cs.ad, "Correo electr\363nico");
        a.put(cs.ae, "Datos de prueba");
        a.put(cs.af, "Sandbox");
        a.put(cs.ag, "Caduca");
        a.put(cs.ah, "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        a.put(cs.ai, "\277Olvid\363 su contrase\361a?");
        a.put(cs.aj, "De");
        a.put(cs.ak, "\277C\363mo le gustar\355a respaldar sus pagos futuros %1$s?");
        a.put(cs.al, "<h1><strong>Acuerdo de pago futuro</strong></h1><p>Su forma de pago predeterminada se utilizar\341 para realizar futuros pagos con PayPal de este vendedor.</p><p>Para cancelar este acuerdo, inicie sesi\363n en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Mi configuraci\363n</strong> &gt; <strong>Iniciar sesi\363n con PayPal</strong> y eliminar a este comercio de la lista.</p><p>Aplicar\341 el art\355culo Pagos recurrentes de las <a href='%s'>Condiciones de uso de PayPal</a>.</p><p>Para asegurarse de que los pagos con tu cuenta PayPal funcionen correctamente, esta aplicaci\363n puede simular una peque\361a transacci\363n de prueba, pero no se transferir\341 dinero.</p>");
        a.put(cs.am, "Error interno");
        a.put(cs.an, "<p>Al hacer clic en el bot\363n a continuaci\363n, por el presente documento acepto los t\351rminos de las <a href='%1$s'>Condiciones de uso de PayPal</a> y declaro que cumplo las leyes y normas japonesas, incluidas las sanciones contra pagos a Corea del Norte e Ir\341n de conformidad con la <a href='%2$s'>Ley de divisas y comercio exterior</a> para realizar la transacci\363n.</p>");
        a.put(cs.ao, "Iniciar sesi\363n");
        a.put(cs.ap, "Iniciar sesi\363n con Paypal");
        a.put(cs.aq, "Cerrar sesi\363n");
        a.put(cs.ar, "Cerrar sesi\363n");
        a.put(cs.as, "Aceptar");
        a.put(cs.at, "Contrase\361a");
        a.put(cs.au, "Pagar despu\351s de la entrega");
        a.put(cs.av, "Pagar con");
        a.put(cs.aw, "Pagar con tarjeta");
        a.put(cs.ax, "Saldo de la cuenta PayPal");
        a.put(cs.ay, "PayPal Credit");
        a.put(cs.az, "Tel\351fono");
        a.put(cs.aA, "NIP");
        a.put(cs.aB, "Forma de pago preferida");
        a.put(cs.aC, "PayPal protege su <a href='%s'>privacidad</a> e informaci\363n financiera.");
        a.put(cs.aD, "Proceso en curso");
        a.put(cs.aE, "Recordar tarjeta");
        a.put(cs.aF, "Solicitar pago");
        a.put(cs.aG, "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a las opciones <strong>Iniciar sesi\363n con PayPal</strong> en la secci\363n de configuraci\363n del <strong>Perfil</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el partner.</p>");
        a.put(cs.aH, "Ahorros");
        a.put(cs.aI, "Enviar un pago");
        a.put(cs.aJ, "Se ha producido un problema en la comunicaci\363n con los servidores de PayPal. Int\351ntelo de nuevo.");
        a.put(cs.aK, "Inicie sesi\363n de nuevo en PayPal.");
        a.put(cs.aL, "Sesi\363n caducada");
        a.put(cs.aM, "Direcci\363n de env\355o");
        a.put(cs.aN, "\277Nuevo usuario de PayPal? Registrarse");
        a.put(cs.aO, "Mantener la sesi\363n activa");
        a.put(cs.aP, "Error de sistema (%s). Int\351ntelo de nuevo m\341s tarde.");
        a.put(cs.aQ, "Int\351ntelo de nuevo");
        a.put(cs.aR, "No logra iniciar sesi\363n, porque la autenticaci\363n de dos factores fue activada para su cuenta.");
        a.put(cs.aS, "C\363digo de seguridad");
        a.put(cs.aT, "Env\355e un mensaje de texto a su tel\351fono. El c\363digo de 6 d\355gitos que reciba ser\341 v\341lido durante 5 minutos.");
        a.put(cs.aU, "Enviando mensaje de texto");
        a.put(cs.aV, "Ingrese el c\363digo de seguridad de 6 d\355gitos.");
        a.put(cs.aW, "Su tel\351fono m\363vil");
        a.put(cs.aX, "Enviar mensaje de texto");
        a.put(cs.aY, "Enviar mensaje de texto de nuevo");
        a.put(cs.aZ, "No es posible iniciar sesi\363n porque se ha activado la autenticaci\363n de dos factores para la cuenta. Visite el sitio web de PayPal para activar su clave de seguridad.");
        a.put(cs.ba, "No se permiten los pagos desde este dispositivo.");
        a.put(cs.bb, "Dispositivo no autorizado");
        a.put(cs.bc, "Los pagos a este comercio no se permiten (id. de cliente no v\341lida).");
        a.put(cs.bd, "Comercio no v\341lido");
        a.put(cs.be, "Hubo un problema al procesar su pago. Int\351ntelo de nuevo.");
        a.put(cs.bf, "Origen no reconocido");
        a.put(cs.bg, "Lo sentimos");
        a.put(cs.bh, "Su pedido");
        a.put(cs.bi, "\277Eliminar tarjeta?");
        a.put(cs.bj, "Error en el permiso");
        a.put(cs.bk, "Error de conexi\363n");
        a.put(cs.bl, "Error de inicio de sesi\363n");
        a.put(cs.bm, "Iniciar sesi\363n con contrase\361a");
        a.put(cs.bn, "Iniciar sesi\363n con NIP");
        a.put(cs.bo, "Un momento\u2026");
        a.put(cs.bp, "Error de pago");
        a.put(cs.bq, "Escanear");
        a.put(cs.br, "C\363digo de seguridad incorrecto. Int\351ntelo de nuevo.");
        a.put(cs.bs, "V\355a");
        a.put(cs.bt, "Error del sistema. Int\351ntelo de nuevo m\341s tarde.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", "Comparta informaci\363n acerca de las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", "Comparta la informaci\363n acerca de las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", "Comparta informaci\363n acerca de las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", "Comparta informaci\363n acerca de las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", "Comparta informaci\363n acerca de las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Comparta con ellos la informaci\363n acerca de las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Comparta las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Comparta las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", "Comparta la informaci\363n acerca de las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", "Comparta informaci\363n acerca de las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", "Comparta la informaci\363n acerca de las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", "Comparta informaci\363n acerca de las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Autorizar cargos</a> correspondientes a futuras compras en %2$s pagadas con PayPal. Le instruye a PayPal de pagar todos los importes solicitados por %3$s.</p><p>Consulte los <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>Pagos recurrentes de PayPal y el Acuerdo de pagos</a> para obtener m\341s informaci\363n.</p>");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Autorizar cargos</a> correspondientes a futuras compras en %2$s pagadas con PayPal. Le instruye a PayPal de pagar todos los importes solicitados por %3$s.</p><p>Consulte los <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>Pagos recurrentes de PayPal y el Acuerdo de pagos</a> para obtener m\341s informaci\363n.</p>");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", "<a href='%1$s'>Autorice cargos</a> para compras futuras realizadas con PayPal. Autorice y d\351 instrucciones a PayPal para que pague todos los importes.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", "<a href='%1$s'>Autorice cargos</a> para compras futuras realizadas con PayPal. Autorice y d\351 instrucciones a PayPal para que pague todos los importes.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", "<a href='%1$s'>Autorice cargos</a> para compras futuras realizadas con PayPal. Autorice y d\351 instrucciones a PayPal para que pague todos los importes.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Preapruebe pagos futuros realizados desde su cuenta PayPal sin tener que identificarse en PayPal cada vez. <a href='%1$s'>Consulte los t\351rminos adicionales</a>, incluidas las formas de pago y c\363mo cancelar pagos futuros.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", "Le permita a %2$s <a href='%1$s'>solicitar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", "Le permita a %2$s <a href='%1$s'>solicitar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", "Le permita a %2$s <a href='%1$s'>solicitar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", "Le permita a %2$s <a href='%1$s'>solicitar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", "Le permita a %2$s <a href='%1$s'>solicitar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", "Le permita a %2$s <a href='%1$s'>solicitar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", "Le permita a %2$s <a href='%1$s'>solicitar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", "Le permita a %2$s <a href='%1$s'>enviar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", "Le permita a %2$s <a href='%1$s'>enviar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", "Le permita a %2$s <a href='%1$s'>enviar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", "Le permita a %2$s <a href='%1$s'>enviar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", "Le permita a %2$s <a href='%1$s'>enviar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", "Le permita a %2$s <a href='%1$s'>enviar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", "Le permita a %2$s <a href='%1$s'>enviar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte informaci\363n sobre qu\351 formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte informaci\363n sobre qu\351 formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte informaci\363n sobre qu\351 formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su utilizaci\363n.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Acuerdo de pago futuro</strong></h1><p>Para asegurarse de que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicaci\363n podr\355a simular una peque\361a transacci\363n de prueba, pero no se transferir\341 dinero alguno.</p><p>Su forma de pago predeterminada (su saldo PayPal, cuenta bancaria asociada, tarjeta de d\351bito o tarjeta de cr\351dito, en ese orden) se utilizar\341 para pagar sus compras de PayPal. Tenga en cuenta que si su forma de pago predeterminada no tiene suficientes fondos para cubrir la compra, su banco o el proveedor de su tarjeta podr\355an cobrarle una comisi\363n.</p><p>Para cancelar este acuerdo, inicie sesi\363n en su cuenta PayPal y vaya a <strong>Perfil</strong>, luego haga clic en <strong>Mi configuraci\363n</strong> y <strong>Cambiar</strong> junto a \253Iniciar sesi\363n con PayPal\273.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Acuerdo de pago futuro</strong></h1><p>Para asegurarse de que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicaci\363n podr\355a simular una peque\361a transacci\363n de prueba, pero no se transferir\341 dinero alguno.</p><p>Su saldo PayPal o tarjeta de d\351bito o cr\351dito principal se utilizar\341n para pagar sus compras de PayPal.</p><p>Para cancelar este acuerdo, inicie sesi\363n en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Mi configuraci\363n</strong> &gt; <strong>Iniciar sesi\363n con PayPal</strong> y eliminar a este comercio de la lista.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Acuerdo de pago futuro</strong></h1><p>Para asegurarse de que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicaci\363n podr\355a simular una peque\361a transacci\363n de prueba, pero no se transferir\341 pago alguno.</p><p>Su forma de pago predeterminada se utilizar\341 para pagar las compras de PayPal.</p><p>Para cancelar este acuerdo, inicie sesi\363n en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Configuraci\363n</strong> &gt; <strong>Iniciar sesi\363n con PayPal</strong> y eliminar a este comercio de la lista.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Acuerdo de pagos futuros</strong></h1><p>Su forma de pago predeterminada se utilizar\341 para realizar futuros pagos con PayPal de este vendedor.</p><p>Para cancelar este acuerdo, inicie sesi\363n en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Mi configuraci\363n</strong> &gt; <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio de la lista.</p><p>Aplicar\341 el art\355culo Pagos recurrentes de las <a href='%s'>Condiciones de uso de PayPal</a>.</p><p>Para asegurarse de que los pagos con tu cuenta PayPal funcionen correctamente, esta aplicaci\363n puede simular una peque\361a transacci\363n de prueba, pero no se transferir\341 dinero.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Autorizaci\363n de pago futuro</strong></h1><p>Para asegurarse de que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicaci\363n podr\355a simular una peque\361a transacci\363n de prueba, pero no se transferir\341 pago alguno.</p><p>Su forma de pago predeterminada se utilizar\341 para pagar las compras de PayPal.</p><p>Para cancelar esta autorizaci\363n, inicie sesi\363n en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Configuraci\363n de mi cuenta</strong> &gt; <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio de la lista.</p><p>Consulte la secci\363n \253Pagos preaprobados\273 de las <a href='%s'>Condiciones de uso de PayPal</a> para obtener m\341s informaci\363n.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Autorizaci\363n de pago futuro</strong></h1><p>Para asegurarse de que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicaci\363n podr\355a simular una peque\361a transacci\363n de prueba, pero no se transferir\341 pago alguno.</p><p>Su forma de pago predeterminada se utilizar\341 para pagar las compras de PayPal.</p><p>Para cancelar esta autorizaci\363n, inicie sesi\363n en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Configuraci\363n de mi cuenta</strong> &gt; <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio de la lista.</p><p>Consulte el art\355culo \253Pagos preaprobados\273 de las <a href='%s'>Condiciones de uso de PayPal</a> para obtener m\341s informaci\363n.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Acuerdo de pago futuro</strong></h1><p>Para asegurarse de que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicaci\363n podr\355a simular una peque\361a transacci\363n de prueba, pero no se transferir\341 dinero alguno.</p><p>Su saldo PayPal o tarjeta de d\351bito o cr\351dito principal se utilizar\341n para pagar sus compras de PayPal.</p><p>Para cancelar este acuerdo, inicie sesi\363n en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Mi configuraci\363n</strong> &gt; <strong>Iniciar sesi\363n con PayPal</strong> y eliminar a este comercio de la lista.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", "<h1><strong>Autorizaci\363n de pago futuro</strong></h1><p>Para asegurarse de que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicaci\363n podr\355a simular una peque\361a transacci\363n de prueba, pero no se transferir\341 pago alguno.</p><p>Su forma de pago predeterminada se utilizar\341 para pagar las compras de PayPal.</p><p>Para cancelar esta autorizaci\363n, inicie sesi\363n en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Configuraci\363n de mi cuenta</strong> &gt; <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio de la lista.</p><p>Consulte la secci\363n \253Pagos preaprobados\273 de las <a href='%s'>Condiciones de uso de PayPal</a> para obtener m\341s informaci\363n.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", "<h1><strong>Autorizaci\363n de pago futuro</strong></h1><p>Para asegurarse de que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicaci\363n podr\355a simular una peque\361a transacci\363n de prueba, pero no se transferir\341 pago alguno.</p><p>Su forma de pago predeterminada se utilizar\341 para pagar las compras de PayPal.</p><p>Para cancelar esta autorizaci\363n, inicie sesi\363n en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Configuraci\363n de mi cuenta</strong> &gt; <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio de la lista.</p><p>Consulte la secci\363n \253Pagos preaprobados\273 de las <a href='%s'>Condiciones de uso de PayPal</a> para obtener m\341s informaci\363n.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Autorizaci\363n de pago futuro</strong></h1><p>Para asegurarse de que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicaci\363n podr\355a simular una peque\361a transacci\363n de prueba, pero no se transferir\341 pago alguno.</p><p>Su forma de pago predeterminada se utilizar\341 para pagar las compras de PayPal.</p><p>Para cancelar esta autorizaci\363n, inicie sesi\363n en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Configuraci\363n de mi cuenta</strong> &gt; <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio de la lista.</p><p>Consulte la secci\363n \253Pagos preaprobados\273 de las <a href='%s'>Condiciones de uso de PayPal</a> para obtener m\341s informaci\363n.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Acuerdo de pago futuro</strong></h1><p>PayPal utilizar\341 primero el saldo de su cuenta PayPal para pagar su compra. Si el saldo no cubre el total, se utilizar\341n las siguientes formas de pago en este orden: cuenta bancaria, PayPal Credit, tarjeta de d\351bito, tarjeta de cr\351dito y/o eCheck.</p><p>Para cancelar este acuerdo, vaya a www.paypal.com <strong>Perfil</strong> &gt; <strong>Mi configuraci\363n</strong> &gt; <strong>Iniciar sesi\363n con PayPal</strong> y eliminar a este comercio de la lista.</p><p>Se puede requerir la autorizaci\363n de un peque\361o pago para garantizar que se puedan hacer cargos en su cuenta PayPal en el futuro. La autorizaci\363n se anular\341 y no se le har\341 ning\372n cobro.</p>");
        b.put("LOG_IN_TO_PAYPAL|AU", "Iniciar sesi\363n con Paypal");
        b.put("LOG_IN_TO_PAYPAL|GB", "Iniciar sesi\363n con Paypal");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el partner.</p><p>Para retirar el permiso, inicie sesi\363n en su cuenta PayPal y haga clic en el icono del engrane. Vaya a <strong>Seguridad</strong>, seleccione <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este partner.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el partner.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a las opciones <strong>Iniciar sesi\363n con PayPal</strong> en la secci\363n de configuraci\363n del <strong>Perfil</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el partner.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en su cuenta PayPal y luego vaya a las opciones <strong>Iniciar sesi\363n con PayPal</strong> en la secci\363n de configuraci\363n de su <strong>Perfil</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el partner.</p><p>Para retirar el permiso, inicie sesi\363n en su cuenta PayPal y haga clic en el icono del engrane. Vaya a <strong>Seguridad</strong>, seleccione <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este partner.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el partner.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el partner.</p><p>Para retirar el permiso, inicie sesi\363n en su cuenta PayPal y haga clic en el icono del engrane. Vaya a <strong>Seguridad</strong>, seleccione <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este partner.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el partner.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en su cuenta PayPal y luego vaya a las opciones <strong>Iniciar sesi\363n con PayPal</strong> en la secci\363n de configuraci\363n del <strong>Perfil</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en su cuenta PayPal, haga clic en el icono del engrane situado en el extremo superior derecho de la pantalla, elija <strong>Centro de Seguridad</strong>, seleccione <strong>Iniciar sesi\363n con PayPal</strong> y elimine al comercio. Si todav\355a est\341 utilizando el sitio web cl\341sico, vaya a <strong>Mi perfil</strong>, seleccione <strong>La configuraci\363n de mi cuenta</strong>, luego seleccione <strong>Iniciar sesi\363n con PayPal</strong> y elimine al comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el partner.</p><p>Para retirar el permiso, inicie sesi\363n en su cuenta PayPal, luego, en la configuraci\363n de <strong>Perfil</strong> vaya a <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este partner.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el partner.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.it y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en su cuenta PayPal y luego vaya a las opciones <strong>Iniciar sesi\363n con PayPal</strong> en la secci\363n de configuraci\363n de su <strong>Perfil</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en su cuenta PayPal y luego vaya a las opciones <strong>Iniciar sesi\363n con PayPal</strong> en la secci\363n de configuraci\363n del <strong>Perfil</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en su cuenta PayPal y luego vaya a las opciones <strong>Iniciar sesi\363n con PayPal</strong> en la secci\363n de configuraci\363n de su <strong>Perfil</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el partner.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.ru, haga clic en el icono del engrane situado en el extremo superior derecho de la pantalla, elija la pesta\361a <strong>Seguridad</strong> y en la opci\363n <strong>Iniciar sesi\363n con PayPal</strong> elimine a este partner.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el partner.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en su cuenta PayPal y luego vaya a las opciones <strong>Iniciar sesi\363n con PayPal</strong> en la secci\363n de configuraci\363n del <strong>Perfil</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com.tr, haga clic en el icono del engrane situado en el extremo superior derecho de la pantalla, elija la pesta\361a <strong>Seguridad</strong> y en la opci\363n <strong>Iniciar sesi\363n con PayPal</strong> elimine a este partner.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a las opciones <strong>Iniciar sesi\363n con PayPal</strong> en la secci\363n de configuraci\363n del <strong>Perfil</strong> y elimine a este comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacci\363n se compartir\341n con el comercio.</p><p>Para retirar el permiso, inicie sesi\363n en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesi\363n con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acci\363n o error cometido por el comercio.</p>");
        c.put("AMOUNT_MISMATCH", "El importe total de los art\355culos del carrito no coincide con el importe de la venta.");
        c.put("AUTHORIZATION_ALREADY_COMPLETED", "Ya se realiz\363 esta autorizaci\363n.");
        c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "La autorizaci\363n est\341 en un estado que no se puede anular.");
        c.put("AUTHORIZATION_EXPIRED", "La autorizaci\363n ha caducado.");
        c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "El Id. de la autorizaci\363n solicitada no existe.");
        c.put("AUTHORIZATION_VOIDED", "La autorizaci\363n se ha anulado.");
        c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Solo puede volver a aprobar la autorizaci\363n original; no una nueva autorizaci\363n.");
        c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "No se permite la nueva autorizaci\363n en el per\355odo de tramitaci\363n.");
        c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "El importe supera el l\355mite aceptable.");
        c.put("CARD_TOKEN_PAYER_MISMATCH", "No puede acceder a la informaci\363n de la tarjeta guardada.");
        c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Los datos de la tarjeta no son v\341lidos. Corr\355jala y env\355ela de nuevo.");
        c.put("CREDIT_CARD_REFUSED", "Tarjeta declinada.");
        c.put("CURRENCY_MISMATCH", "La divisa de la captura debe ser igual que la divisa de la autorizaci\363n.");
        c.put("CURRENCY_NOT_ALLOWED", "Esta divisa no es compatible actualmente con PayPal.");
        c.put("DATA_RETRIEVAL", "Error del sistema. Int\351ntelo de nuevo m\341s tarde.");
        c.put("DUPLICATE_REQUEST_ID", "Error del sistema. Int\351ntelo de nuevo m\341s tarde.");
        c.put("EXPIRED_CREDIT_CARD", "La tarjeta ha vencido");
        c.put("EXPIRED_CREDIT_CARD_TOKEN", "Los datos de esta tarjeta ya no est\341n registrados.\nEnv\355elos nuevamente.");
        c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Funci\363n no disponible para este vendedor.");
        c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Esta transacci\363n se ha reembolsado parcialmente.");
        c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Pago inmediato no compatible con la finalidad transmitida.");
        c.put("INSTRUMENT_DECLINED", "No se ha aceptado la forma de pago seleccionada. Seleccione otra forma de pago.");
        c.put("INSUFFICIENT_FUNDS", "El comprador no puede pagar - saldo insuficiente.");
        c.put("INTERNAL_SERVICE_ERROR", "Error del sistema. Int\351ntelo de nuevo m\341s tarde.");
        c.put("INVALID_ACCOUNT_NUMBER", "Ese n\372mero de cuenta no existe.");
        c.put("INVALID_ARGUMENT", "La transacci\363n se declin\363 debido a un argumento no v\341lido");
        c.put("INVALID_CITY_STATE_ZIP", "Combinaci\363n de ciudad/estado/c\363digo postal no v\341lida.");
        c.put("INVALID_FACILITATOR_CONFIGURATION", "Esta transacci\363n no puede procesarse debido a una configuraci\363n no v\341lida del facilitador.");
        c.put("INVALID_PAYER_ID", "Error del sistema (la id. del pagador no es v\341lida). Int\351ntelo de nuevo m\341s tarde.");
        c.put("INVALID_RESOURCE_ID", "Error del sistema. Int\351ntelo de nuevo m\341s tarde.");
        c.put("PAYEE_ACCOUNT_INVALID", "La cuenta del proveedor no tiene un correo electr\363nico confirmado.");
        c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Este proveedor no puede recibir pagos por el momento.");
        c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "La cuenta del proveedor no tiene un correo electr\363nico confirmado.");
        c.put("PAYEE_ACCOUNT_RESTRICTED", "Este proveedor no puede recibir pagos por el momento.");
        c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Su cuenta est\341 bloqueada o cerrada.");
        c.put("PAYER_ACCOUNT_RESTRICTED", "Su cuenta est\341 restringida.");
        c.put("PAYER_CANNOT_PAY", "No puede pagar esta transacci\363n con PayPal.");
        c.put("PAYER_EMPTY_BILLING_ADDRESS", "La direcci\363n de facturaci\363n es obligatoria para las transacciones con tarjetas de cr\351dito que no sean de PayPal.");
        c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "No puede acceder a la informaci\363n de la tarjeta guardada.");
        c.put("PAYMENT_APPROVAL_EXPIRED", "La aprobaci\363n del pago ha vencido.");
        c.put("PAYMENT_EXPIRED", "El pago ha vencido.");
        c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "El pagador no ha aprobado el pago.");
        c.put("PAYMENT_REQUEST_ID_INVALID", "El Id. de la solicitud de PayPal no es v\341lido. Int\351ntelo de nuevo m\341s tarde.");
        c.put("PAYMENT_STATE_INVALID", "Esta solicitud no es v\341lida debido al estado actual del pago.");
        c.put("PERMISSION_DENIED", "No hay permiso para la operaci\363n solicitada.");
        c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "El reembolso solicitado supera el importe de la transacci\363n original.");
        c.put("REFUND_TIME_LIMIT_EXCEEDED", "Esta transacci\363n es muy antigua para reembolsarse.");
        c.put("REQUIRED_SCOPE_MISSING", "Error del sistema. Int\351ntelo de nuevo m\341s tarde.");
        c.put("TOO_MANY_REAUTHORIZATIONS", "No se permiten nuevas autorizaciones para esta autorizaci\363n.");
        c.put("TRANSACTION_ALREADY_REFUNDED", "El importe de esta transacci\363n ya se ha reembolsado.");
        c.put("TRANSACTION_LIMIT_EXCEEDED", "El importe supera el l\355mite aceptable.");
        c.put("TRANSACTION_REFUSED", "La transacci\363n se ha declinado.");
        c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "La transacci\363n se ha declinado.");
        c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Hay una preferencia de perfil definida para rechazar autom\341ticamente todas las transacciones.");
        c.put("UNKNOWN_ERROR", "Error del sistema. Int\351ntelo de nuevo m\341s tarde.");
        c.put("UNSUPPORTED_PAYEE_COUNTRY", "No disponible en su pa\355s.");
        c.put("VALIDATION_ERROR", "La informaci\363n de pago no es v\341lida. Corr\355jala y env\355ela de nuevo.");
        c.put("ORDER_ALREADY_COMPLETED", "El pedido ya fue anulado, ha caducado o fue realizado.");
        c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Se ha llegado al n\372mero m\341ximo de autorizaciones permitidas para el pedido.");
        c.put("ORDER_VOIDED", "El pedido se ha anulado.");
        c.put("ORDER_CANNOT_BE_VOIDED", "El pedido est\341 en un estado que previene la anulaci\363n.");
        c.put("INVALID_EXPERIENCE_PROFILE_ID", "Error del sistema. Int\351ntelo de nuevo m\341s tarde.");
        c.put("UNAUTHORIZED_PAYMENT", "El comercio no acepta este tipo de pagos.");
        c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Divisa no compatible para el tipo de tarjeta.");
        c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Tipo de tarjeta no compatible.");
        c.put("ADDRESS_ADDITION_ERROR", "Error encontrado al agregar direcci\363n de env\355o a cuenta PayPal.");
        c.put("DUPLICATE_TRANSACTION", "Transacci\363n duplicada.");
        c.put("INVALID_SHIPPING_ADDRESS", "La direcci\363n de env\355o suministrada no es v\341lida.");
        c.put("PAYMENT_CREATION_ERROR", "Se ha producido un problema al configurar este pago. Visite el sitio web de PayPal para revisar su cuenta.");
        c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Se ha producido un problema al configurar este pago: su tarjeta ha vencido. Visite el sitio web de PayPal para revisar su cuenta.");
        c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Se ha producido un problema al configurar este pago: se requiere un pago instant\341neo, como una tarjeta de cr\351dito. Visite el sitio web de PayPal para revisar su cuenta.");
        c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Se ha producido un problema al configurar este pago: la tarjeta debe estar confirmada. Visite el sitio web de PayPal para revisar su cuenta.");
        c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Se ha producido un problema al configurar este pago: esta aplicaci\363n requiere que su cuenta incluya un n\372mero de tel\351fono. Visite el sitio web de PayPal para revisar su cuenta.");
        c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Se ha producido un problema al configurar este pago: la cuenta necesita una forma de pago v\341lida, como una cuenta bancaria o tarjeta de pago. Visite el sitio web de PayPal para revisar su cuenta.");
        c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Se ha producido un problema al configurar este pago: su saldo es negativo. Visite el sitio web de PayPal para revisar su cuenta.");
        c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Se ha producido un problema al configurar este pago: ha alcanzado su l\355mite de env\355o. Visite el sitio web de PayPal para revisar su cuenta.");
        c.put("AUTH_RC_RISK_FAILURE", "Declinado debido a riesgo.");
        c.put("AUTH_RC_OFAC_BLOCKED_IP", "Cliente no autorizado.");
        c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Cliente no autorizado.");
        c.put("invalid_user", "Nombre de usuario o contrase\361a incorrectos. Int\351ntelo de nuevo.");
        c.put("locked_user", "Su cuenta PayPal ha sido bloqueada temporalmente. Int\351ntelo de nuevo m\341s tarde o visite www.paypal.com para desbloquear inmediatamente su cuenta PayPal.");
        c.put("max_attempts_exceeded", "Demasiados intentos fallidos de inicio de sesi\363n. Int\351ntelo de nuevo m\341s tarde.");
        c.put("invalid_request", "Ha habido un error.");
        c.put("unauthorized_client", "Solicitud no autorizada.");
        c.put("access_denied", "Solicitud no autorizada.");
        c.put("unsupported_response_type", "Ha habido un error.");
        c.put("invalid_scope", "Solicitud no autorizada.");
        c.put("server_error", "Error del sistema. Int\351ntelo de nuevo m\341s tarde.");
        c.put("temporarily_unavailable", "Error del sistema. Int\351ntelo de nuevo m\341s tarde.");
    }

    public final String a()
    {
        return "es_MX";
    }

    public final String a(Enum enum, String s)
    {
        enum = (cs)enum;
        s = (new StringBuilder()).append(enum.toString()).append("|").append(s).toString();
        if (b.containsKey(s))
        {
            return (String)b.get(s);
        } else
        {
            return (String)a.get(enum);
        }
    }

    public final String a(String s)
    {
        return (String)c.get(s);
    }

}
