// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.contextlogic.wish.analytics;


public final class WishAnalyticsEvent extends Enum
{

    private static final WishAnalyticsEvent $VALUES[];
    public static final WishAnalyticsEvent CLICK_CART_EDUCATION_MODAL_BUTTON;
    public static final WishAnalyticsEvent CLICK_CART_TIMER;
    public static final WishAnalyticsEvent CLICK_CROSS_PROMO_BANNER;
    public static final WishAnalyticsEvent CLICK_CROSS_PROMO_BUY_BLOCKER_ACTION;
    public static final WishAnalyticsEvent CLICK_CROSS_PROMO_BUY_BLOCKER_CANCEL;
    public static final WishAnalyticsEvent CLICK_DEAL_DASH_GO_TO_CART_MODAL;
    public static final WishAnalyticsEvent CLICK_DEAL_DASH_LEAVE;
    public static final WishAnalyticsEvent CLICK_DEAL_DASH_START;
    public static final WishAnalyticsEvent CLICK_DEAL_DASH_TAB;
    public static final WishAnalyticsEvent CLICK_GIFT_GIFT_IT_BUTTON;
    public static final WishAnalyticsEvent CLICK_MOBILE_ABANDONED_CART_NOTIFICATION;
    public static final WishAnalyticsEvent CLICK_MOBILE_ADDED_TO_CART_MODAL_SHOP;
    public static final WishAnalyticsEvent CLICK_MOBILE_ADDED_TO_CART_MODAL_VIEW_CART;
    public static final WishAnalyticsEvent CLICK_MOBILE_ADD_TO_CART_BUY;
    public static final WishAnalyticsEvent CLICK_MOBILE_ADD_TO_CART_CANCEL;
    public static final WishAnalyticsEvent CLICK_MOBILE_APP_LIST_ITEM;
    public static final WishAnalyticsEvent CLICK_MOBILE_BILLING_AUTOFILL_DISMISS;
    public static final WishAnalyticsEvent CLICK_MOBILE_BILLING_AUTOFILL_TOAST;
    public static final WishAnalyticsEvent CLICK_MOBILE_BILLING_AUTOFILL_TOAST_MIN;
    public static final WishAnalyticsEvent CLICK_MOBILE_BILLING_AUTOFILL_TOAST_SUC;
    public static final WishAnalyticsEvent CLICK_MOBILE_CART_CONTINUE_SHOPPING;
    public static final WishAnalyticsEvent CLICK_MOBILE_CART_GET_CREDIT;
    public static final WishAnalyticsEvent CLICK_MOBILE_CART_ITEM_CHANGE;
    public static final WishAnalyticsEvent CLICK_MOBILE_CHOME_CATEGORY;
    public static final WishAnalyticsEvent CLICK_MOBILE_CHOME_COLLECTION;
    public static final WishAnalyticsEvent CLICK_MOBILE_DEEP_LINK_SORT_MODE;
    public static final WishAnalyticsEvent CLICK_MOBILE_DETAILS_CHANGE_RELATED_TAB;
    public static final WishAnalyticsEvent CLICK_MOBILE_DETAILS_GET_CREDIT;
    public static final WishAnalyticsEvent CLICK_MOBILE_DETAILS_MERCHANT_RATING;
    public static final WishAnalyticsEvent CLICK_MOBILE_DETAILS_MERCHANT_STORE;
    public static final WishAnalyticsEvent CLICK_MOBILE_DETAILS_PRODUCT_RATING;
    public static final WishAnalyticsEvent CLICK_MOBILE_DETAILS_SEARCH;
    public static final WishAnalyticsEvent CLICK_MOBILE_DETAILS_VIEW_DESCRIPTION;
    public static final WishAnalyticsEvent CLICK_MOBILE_EMAIL_CHANGE_PASSWORD;
    public static final WishAnalyticsEvent CLICK_MOBILE_EMAIL_FORGOT_PASSWORD;
    public static final WishAnalyticsEvent CLICK_MOBILE_EMAIL_LOGIN;
    public static final WishAnalyticsEvent CLICK_MOBILE_EMAIL_SIGN_UP;
    public static final WishAnalyticsEvent CLICK_MOBILE_EMAIL_UPDATE_PROFILE_NEXT;
    public static final WishAnalyticsEvent CLICK_MOBILE_EMAIL_UPDATE_PROFILE_SKIP;
    public static final WishAnalyticsEvent CLICK_MOBILE_EXTRA_PHOTOS;
    public static final WishAnalyticsEvent CLICK_MOBILE_FEED_ENDED_WIDGET;
    public static final WishAnalyticsEvent CLICK_MOBILE_FEED_EXTRA_PHOTOS;
    public static final WishAnalyticsEvent CLICK_MOBILE_FEED_FILTER_APPLY;
    public static final WishAnalyticsEvent CLICK_MOBILE_FEED_FILTER_CANCEL;
    public static final WishAnalyticsEvent CLICK_MOBILE_FEED_FILTER_NAV;
    public static final WishAnalyticsEvent CLICK_MOBILE_FEED_FILTER_REMOVE;
    public static final WishAnalyticsEvent CLICK_MOBILE_FEED_FILTER_SEARCH;
    public static final WishAnalyticsEvent CLICK_MOBILE_FEED_FILTER_SELECT;
    public static final WishAnalyticsEvent CLICK_MOBILE_FREE_GIFT_ABANDONMENT_MODAL_PROCEED;
    public static final WishAnalyticsEvent CLICK_MOBILE_FREE_GIFT_ABANDONMENT_MODAL_RETURN;
    public static final WishAnalyticsEvent CLICK_MOBILE_FREE_GIFT_ADD_TO_CART_MODAL_BUY;
    public static final WishAnalyticsEvent CLICK_MOBILE_FREE_GIFT_ADD_TO_CART_MODAL_CANCEL;
    public static final WishAnalyticsEvent CLICK_MOBILE_FREE_GIFT_APPLIED_MODAL_CONTINUE;
    public static final WishAnalyticsEvent CLICK_MOBILE_FREE_GIFT_BILLING_BACK_BUTTON;
    public static final WishAnalyticsEvent CLICK_MOBILE_FREE_GIFT_BILLING_CANCEL_BUTTON;
    public static final WishAnalyticsEvent CLICK_MOBILE_FREE_GIFT_BILLING_REDEEM_BUTTON;
    public static final WishAnalyticsEvent CLICK_MOBILE_FREE_GIFT_CLAIM_BUTTON;
    public static final WishAnalyticsEvent CLICK_MOBILE_FREE_GIFT_CLAIM_CANCEL_BUTTON;
    public static final WishAnalyticsEvent CLICK_MOBILE_FREE_GIFT_SCROLL_PRODUCT;
    public static final WishAnalyticsEvent CLICK_MOBILE_FREE_GIFT_SHIPPING_BACK_BUTTON;
    public static final WishAnalyticsEvent CLICK_MOBILE_FREE_GIFT_SHIPPING_CANCEL_BUTTON;
    public static final WishAnalyticsEvent CLICK_MOBILE_FREE_GIFT_SHIPPING_NEXT_BUTTON;
    public static final WishAnalyticsEvent CLICK_MOBILE_FREE_GIFT_SHIPPING_SAME_AS_CHECKBOX;
    public static final WishAnalyticsEvent CLICK_MOBILE_GIFTING_BUY_MORE_GIFTS;
    public static final WishAnalyticsEvent CLICK_MOBILE_GIFTING_DASH_COLLECTION;
    public static final WishAnalyticsEvent CLICK_MOBILE_GIFTING_DASH_FB_LOGIN;
    public static final WishAnalyticsEvent CLICK_MOBILE_GIFTING_DASH_FRIEND_FACE;
    public static final WishAnalyticsEvent CLICK_MOBILE_GIFTING_DASH_FRIEND_FEED;
    public static final WishAnalyticsEvent CLICK_MOBILE_GIFTING_DASH_SLIDER_FEED;
    public static final WishAnalyticsEvent CLICK_MOBILE_GIFTING_DONE_BUYING_GIFTS;
    public static final WishAnalyticsEvent CLICK_MOBILE_GIFTING_EDIT_BILLING;
    public static final WishAnalyticsEvent CLICK_MOBILE_GIFTING_EDIT_SHIPPING;
    public static final WishAnalyticsEvent CLICK_MOBILE_GIFTING_NATIVE_CHECKOUT;
    public static final WishAnalyticsEvent CLICK_MOBILE_GIFTING_PLACE_ORDER;
    public static final WishAnalyticsEvent CLICK_MOBILE_GIFTING_PLACE_ORDER_FAILURE;
    public static final WishAnalyticsEvent CLICK_MOBILE_GIFTING_PLACE_ORDER_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_HOME;
    public static final WishAnalyticsEvent CLICK_MOBILE_INVITE_BY_LINK_DONE;
    public static final WishAnalyticsEvent CLICK_MOBILE_INVITE_BY_LINK_EMAIL;
    public static final WishAnalyticsEvent CLICK_MOBILE_INVITE_BY_LINK_PROMPT_DONE;
    public static final WishAnalyticsEvent CLICK_MOBILE_INVITE_BY_LINK_PROMPT_EMAIL;
    public static final WishAnalyticsEvent CLICK_MOBILE_INVITE_BY_LINK_PROMPT_SHARE;
    public static final WishAnalyticsEvent CLICK_MOBILE_INVITE_BY_LINK_PROMPT_SMS;
    public static final WishAnalyticsEvent CLICK_MOBILE_INVITE_BY_LINK_SHARE;
    public static final WishAnalyticsEvent CLICK_MOBILE_INVITE_BY_LINK_SMS;
    public static final WishAnalyticsEvent CLICK_MOBILE_LIVE_SUPPORT_CART;
    public static final WishAnalyticsEvent CLICK_MOBILE_LIVE_SUPPORT_PENDING;
    public static final WishAnalyticsEvent CLICK_MOBILE_LIVE_SUPPORT_PROD_DETAILS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_AUTO_PLACE_ORDER;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_AUTO_PLACE_ORDER_FAILURE;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_AUTO_PLACE_ORDER_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_BOKU_TAB;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_BOLETO_TAB;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_CC_TAB;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_FRIEND_FAMILY_TAB;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_GWALLET_TAB;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_NEXT_BOKU;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_NEXT_BOLETO;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_NEXT_BOLETO_FAILURE;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_NEXT_BOLETO_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_NEXT_CC;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_NEXT_CC_FAILURE;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_NEXT_CC_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_NEXT_FACEBOOK;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_NEXT_FAMILY;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_NEXT_FAMILY_FAILURE;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_NEXT_FAMILY_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_NEXT_GWALLET;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_NEXT_OXXO;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_NEXT_OXXO_FAILURE;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_NEXT_OXXO_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_NEXT_PAYPAL;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_OXXO_TAB;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_PAYPAL_TAB;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_SAVE_VISA;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_SAVE_VISA_FAILURE;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_SAVE_VISA_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_SCAN;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_SCAN_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_VISA_CANCEL;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_VISA_ERROR;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_VISA_FETCHED;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_VISA_START;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_VISA_TAB;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BILLING_ZIP_NEXT;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BOKU_INITIATE_ORDER;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BOKU_INITIATE_ORDER_FAILURE;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BOKU_INITIATE_ORDER_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BOLETO_PLACE_ORDER;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BOLETO_PLACE_ORDER_FAILURE;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BOLETO_PLACE_ORDER_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_BUY_WITH_GOOGLE;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_CATEGORY;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_CATEGORY_END_SCROLL;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_CATEGORY_START_SCROLL;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_CHECKOUT;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_COLLECTION;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_COLLECTION_END_SCROLL;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_COLLECTION_START_SCROLL;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_EDIT_BILLING;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_EDIT_BILLING_EMPTY;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_EDIT_SHIPPING;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_EDIT_SHIPPING_EMPTY;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_FACEBOOK_AUTO_ORDER;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_FACEBOOK_ORDER;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_FACEBOOK_ORDER_FAILURE;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_FACEBOOK_ORDER_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_FAMILY_PLACE_ORDER;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_FAMILY_PLACE_ORDER_FAILURE;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_FAMILY_PLACE_ORDER_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_FOOTER_COLLECTION;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_FOOTER_COLLECTION_END_SCROLL;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_FOOTER_COLLECTION_START_SCROLL;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_GWALLET_CHANGE_SHIPPING;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_GWALLET_FETCH;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_GWALLET_FETCH_FAILURE;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_GWALLET_FETCH_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_GWALLET_FULL_FAILURE;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_GWALLET_FULL_FETCH;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_GWALLET_FULL_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_GWALLET_ORDER;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_GWALLET_ORDER_FAILURE;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_GWALLET_ORDER_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_MERCHANT_CHANGE_TAB;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_MERCHANT_VIEW_RATING;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_OXXO_PLACE_ORDER;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_OXXO_PLACE_ORDER_FAILURE;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_OXXO_PLACE_ORDER_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_PAYPAL_AUTH_ERROR;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_PAYPAL_AUTH_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_PAYPAL_AUTO_ORDER;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_PAYPAL_CANCEL;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_PAYPAL_FAILURE;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_PAYPAL_FUTURE_PAY_ERROR;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_PAYPAL_FUTURE_PAY_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_PAYPAL_ORDER;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_PAYPAL_PAY_ERROR;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_PAYPAL_PAY_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_PAYPAL_PREPAY_ERROR;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_PAYPAL_PREPAY_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_PAYPAL_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_PAYPAL_VERIFY_ERROR;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_PAYPAL_VERIFY_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_PLACE_ORDER;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_PLACE_ORDER_FAILURE;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_PLACE_ORDER_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_SHIPPING_NEXT;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_SHIPPING_NEXT_FAILURE;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_SHIPPING_NEXT_SUCCESS;
    public static final WishAnalyticsEvent CLICK_MOBILE_NATIVE_SIZING_CHART;
    public static final WishAnalyticsEvent CLICK_MOBILE_PRODUCT_DETAIL_SECTION;
    public static final WishAnalyticsEvent CLICK_MOBILE_RATINGS_VIEW_PRODUCT;
    public static final WishAnalyticsEvent CLICK_MOBILE_RATINGS_VISIT_STORE;
    public static final WishAnalyticsEvent CLICK_MOBILE_RECOMMEND;
    public static final WishAnalyticsEvent CLICK_MOBILE_REQUEST_GIFT_CARD;
    public static final WishAnalyticsEvent CLICK_MOBILE_REQUEST_GIFT_CARD_CONFIRM;
    public static final WishAnalyticsEvent CLICK_MOBILE_SALE_PARTY_SELL;
    public static final WishAnalyticsEvent CLICK_MOBILE_SALE_PARTY_SHOP;
    public static final WishAnalyticsEvent CLICK_MOBILE_SEARCH;
    public static final WishAnalyticsEvent CLICK_MOBILE_SEARCH_FRIEND;
    public static final WishAnalyticsEvent CLICK_MOBILE_SEARCH_HISTORY;
    public static final WishAnalyticsEvent CLICK_MOBILE_SEARCH_POPULAR;
    public static final WishAnalyticsEvent CLICK_MOBILE_SEARCH_PRODUCT;
    public static final WishAnalyticsEvent CLICK_MOBILE_SELL_ADD_EXTRA_PHOTO;
    public static final WishAnalyticsEvent CLICK_MOBILE_SELL_CAMERA_GALLERY;
    public static final WishAnalyticsEvent CLICK_MOBILE_SELL_CAMERA_TAKE_PIC;
    public static final WishAnalyticsEvent CLICK_MOBILE_SELL_CANCEL;
    public static final WishAnalyticsEvent CLICK_MOBILE_SELL_EDU_CHANGE_PAGE;
    public static final WishAnalyticsEvent CLICK_MOBILE_SELL_EDU_GET_STARTED;
    public static final WishAnalyticsEvent CLICK_MOBILE_SELL_EDU_LEARN;
    public static final WishAnalyticsEvent CLICK_MOBILE_SELL_EDU_SKIP;
    public static final WishAnalyticsEvent CLICK_MOBILE_SELL_IMAGE_CANCEL;
    public static final WishAnalyticsEvent CLICK_MOBILE_SELL_IMAGE_CONFIRM;
    public static final WishAnalyticsEvent CLICK_MOBILE_SELL_SUBMIT;
    public static final WishAnalyticsEvent CLICK_MOBILE_SHIPPING_AUTOFILL_TOAST;
    public static final WishAnalyticsEvent CLICK_MOBILE_SHIPPING_AUTOFILL_TOAST_MIN;
    public static final WishAnalyticsEvent CLICK_MOBILE_SHIPPING_AUTOFILL_TOAST_SUC;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIDE_FAQ;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIDE_NAV_CART;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIDE_NAV_HELP;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIDE_NAV_INVITE;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIDE_NAV_NOTIFICATIONS;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIDE_NAV_ORDER_HISTORY;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIDE_NAV_OTHER_APPS;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIDE_NAV_PROFILE;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIDE_NAV_SALE_PARTY;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIDE_NAV_SEARCH;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIDE_NAV_SELL;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIDE_NAV_SETTINGS;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIDE_NAV_UPCOMMING_BIRTHDAY;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIDE_NAV_WALLET;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIGNUP_CATEGORY_NEXT;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIGNUP_EMAIL_CONFIRM_FAIL;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIGNUP_EMAIL_SUGGEST;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIGNUP_GIFTING_SKIP;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIGNUP_INTROGRAPHIC_NEXT;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIGNUP_INTROGRAPHIC_SKIP;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIGNUP_STEP_THREE_NEXT;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIGNUP_SUCCESS_WITH_BOTH;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIGNUP_SUCCESS_WITH_CONFIRM;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIGNUP_SUCCESS_WITH_NONE;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIGNUP_SUCCESS_WITH_SUGGEST;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIGNUP_UPDATE_PROFILE_NEXT;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIGNUP_UPDATE_PROFILE_SKIP;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIGNUP_VIEW_WITH_BOTH;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIGNUP_VIEW_WITH_CONFIRM;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIGNUP_VIEW_WITH_NONE;
    public static final WishAnalyticsEvent CLICK_MOBILE_SIGNUP_VIEW_WITH_SUGGEST;
    public static final WishAnalyticsEvent CLICK_MOBILE_SORT_MODE;
    public static final WishAnalyticsEvent CLICK_MOBILE_SPLASH_EMAIL_LOGIN;
    public static final WishAnalyticsEvent CLICK_MOBILE_SPLASH_EMAIL_SIGN_UP;
    public static final WishAnalyticsEvent CLICK_MOBILE_SPLASH_FACEBOOK_LOGIN;
    public static final WishAnalyticsEvent CLICK_MOBILE_UPSELL_MODAL_BUY_BUTTON;
    public static final WishAnalyticsEvent CLICK_MOBILE_UPSELL_MODAL_NO_THANKS_BUTTON;
    public static final WishAnalyticsEvent CLICK_MOBILE_UPSELL_MODAL_PRODUCT_SCROLL;
    public static final WishAnalyticsEvent CLICK_MOBILE_WALLET_ITEM;
    public static final WishAnalyticsEvent CLICK_MOBILE_ZOOM_PRODUCT_PHOTO;
    public static final WishAnalyticsEvent CLICK_RATING_PHOTO;
    public static final WishAnalyticsEvent CLICK_RELATED_PRODUCT;
    public static final WishAnalyticsEvent CLICK_SCROLL_MAIN_PRODUCT_IMAGE;
    public static final WishAnalyticsEvent CLICK_WISHLOOK_BANNER;
    public static final WishAnalyticsEvent CLICK_WISH_TO_CART_MODAL_BUY;
    public static final WishAnalyticsEvent CLICK_WISH_TO_CART_MODAL_CANCEL;
    public static final WishAnalyticsEvent IMPRESSION_CART_EDUCATION_MODAL;
    public static final WishAnalyticsEvent IMPRESSION_CROSS_PROMO_BANNER;
    public static final WishAnalyticsEvent IMPRESSION_CROSS_PROMO_BUY_BLOCKER;
    public static final WishAnalyticsEvent IMPRESSION_DEAL_DASH_COUNTDOWN;
    public static final WishAnalyticsEvent IMPRESSION_DEAL_DASH_FEED;
    public static final WishAnalyticsEvent IMPRESSION_DEAL_DASH_MODAL;
    public static final WishAnalyticsEvent IMPRESSION_DEAL_DASH_START;
    public static final WishAnalyticsEvent IMPRESSION_DEAL_DASH_WAIT;
    public static final WishAnalyticsEvent IMPRESSION_FIRST_LAUNCH;
    public static final WishAnalyticsEvent IMPRESSION_FREE_GIFTS_ABANDONMENT_MODAL;
    public static final WishAnalyticsEvent IMPRESSION_LOGIN_NOT_FROM_WISH_NOTIFICATION;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_ABANDONED_CART_NOTIFICATION;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_ADDED_TO_CART_MODAL;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_CART;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_CART_ABANDON_OFFER;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_CHECKOUT_OFFER;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_CREDIT_BANNER;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_CREDIT_COUNTER;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_EMAIL_CHANGE_PASSWORD;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_EMAIL_FORGOT_PASSWORD;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_EMAIL_LOGIN;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_EMAIL_SIGN_UP;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_EMAIL_UPDATE_PROFILE;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_FACEBOOK_AUTOFILLED_MSG;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_FACEBOOK_AUTOFILL_TOAST;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_FEED_ENDED_WIDGET;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_FEED_FILTER;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_FREE_GIFTS_SCREEN;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_FREE_GIFT_ADD_TO_CART_MODAL;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_FREE_GIFT_APPLIED_MODAL;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_FREE_GIFT_BILLING_ERROR_MODAL;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_FREE_GIFT_BILLING_INFO;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_FREE_GIFT_SHIPPING_ERROR_MODAL;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_FREE_GIFT_SHIPPING_INFO;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_GOOGLE_APPINDEXING_APP_GOOGLE;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_GOOGLE_APPINDEXING_APP_OTHER;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_GOOGLE_APPINDEXING_CRAWLER;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_GOOGLE_APPINDEXING_WEB_GOOGLE;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_GOOGLE_APPINDEXING_WEB_OTHER;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_INVITE_FRIENDS_BY_LINK;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_INVITE_FRIENDS_BY_LINK_PROMPT;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_LIVE_SUPPORT_CART;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_LIVE_SUPPORT_PENDING;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_LIVE_SUPPORT_PROD_DETAILS;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_NATIVE_BILLING;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_NATIVE_BILLING_ZIP_PAGE;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_NATIVE_GIFT_CART;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_NATIVE_GIFT_COMPLETE;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_NATIVE_GIFT_DASHBOARD;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_NATIVE_GIFT_DETAILS;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_NATIVE_GIFT_EDIT_BILLING;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_NATIVE_GIFT_EDIT_SHIPPING;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_NATIVE_GIFT_FEED;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_NATIVE_MERCHANT_PAGE;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_NATIVE_MERCHANT_RATINGS;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_NATIVE_PRODUCT_RATINGS;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_NATIVE_SHIPPING;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_RATE_TRANSACTION_PROMPT;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_REQUEST_GIFT_CARD;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_REQUEST_GIFT_CARD_CONFIRM;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_REVIEW_CART;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SALE_PARTY;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SELL_CAMERA;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SELL_EDITOR;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SELL_EDU;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SELL_IMAGE_CONFIRM;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SIGNUP_CATEGORY;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SIGNUP_GIFT_CART;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SIGNUP_GIFT_COMPLETE;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SIGNUP_GIFT_DASHBOARD;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SIGNUP_GIFT_DETAILS;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SIGNUP_GIFT_EDIT_BILLING;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SIGNUP_GIFT_EDIT_SHIPPING;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SIGNUP_GIFT_FEED;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SIGNUP_INTROGRAPHIC_PAGE_ONE;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SIGNUP_INTROGRAPHIC_PAGE_THREE;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SIGNUP_INTROGRAPHIC_PAGE_TWO;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SIGNUP_NIAGARA_STEP_FOUR;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SIGNUP_NIAGARA_STEP_THREE;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SIGNUP_NIAGARA_STEP_TWO;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SIGNUP_STEP_ONE;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SIGNUP_STEP_THREE;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SIGNUP_STEP_TWO;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_SIGNUP_UPDATE_PROFILE;
    public static final WishAnalyticsEvent IMPRESSION_MOBILE_UPSELL_MODAL;
    public static final WishAnalyticsEvent IMPRESSION_MY_PROFILE;
    public static final WishAnalyticsEvent IMPRESSION_OTHER_PROFILE;
    public static final WishAnalyticsEvent IMPRESSION_SIGNUP_NOT_FROM_WISH_NOTIFICATION;
    public static final WishAnalyticsEvent IMPRESSION_WISH_TO_CART_MODAL;
    private int value;

    private WishAnalyticsEvent(String s, int i, int j)
    {
        super(s, i);
        value = j;
    }

    public static WishAnalyticsEvent valueOf(String s)
    {
        return (WishAnalyticsEvent)Enum.valueOf(com/contextlogic/wish/analytics/WishAnalyticsEvent, s);
    }

    public static WishAnalyticsEvent[] values()
    {
        return (WishAnalyticsEvent[])$VALUES.clone();
    }

    public int getValue()
    {
        return value;
    }

    static 
    {
        IMPRESSION_MOBILE_SIGNUP_STEP_ONE = new WishAnalyticsEvent("IMPRESSION_MOBILE_SIGNUP_STEP_ONE", 0, 110);
        IMPRESSION_MOBILE_SIGNUP_STEP_TWO = new WishAnalyticsEvent("IMPRESSION_MOBILE_SIGNUP_STEP_TWO", 1, 111);
        IMPRESSION_MOBILE_SIGNUP_STEP_THREE = new WishAnalyticsEvent("IMPRESSION_MOBILE_SIGNUP_STEP_THREE", 2, 112);
        IMPRESSION_MOBILE_SIGNUP_NIAGARA_STEP_TWO = new WishAnalyticsEvent("IMPRESSION_MOBILE_SIGNUP_NIAGARA_STEP_TWO", 3, 113);
        IMPRESSION_MOBILE_SIGNUP_NIAGARA_STEP_THREE = new WishAnalyticsEvent("IMPRESSION_MOBILE_SIGNUP_NIAGARA_STEP_THREE", 4, 114);
        IMPRESSION_MOBILE_SIGNUP_NIAGARA_STEP_FOUR = new WishAnalyticsEvent("IMPRESSION_MOBILE_SIGNUP_NIAGARA_STEP_FOUR", 5, 115);
        IMPRESSION_MOBILE_CART = new WishAnalyticsEvent("IMPRESSION_MOBILE_CART", 6, 128);
        IMPRESSION_MOBILE_NATIVE_SHIPPING = new WishAnalyticsEvent("IMPRESSION_MOBILE_NATIVE_SHIPPING", 7, 129);
        IMPRESSION_MOBILE_NATIVE_BILLING = new WishAnalyticsEvent("IMPRESSION_MOBILE_NATIVE_BILLING", 8, 130);
        IMPRESSION_MOBILE_SELL_CAMERA = new WishAnalyticsEvent("IMPRESSION_MOBILE_SELL_CAMERA", 9, 131);
        IMPRESSION_MOBILE_SELL_IMAGE_CONFIRM = new WishAnalyticsEvent("IMPRESSION_MOBILE_SELL_IMAGE_CONFIRM", 10, 132);
        IMPRESSION_MOBILE_SELL_EDITOR = new WishAnalyticsEvent("IMPRESSION_MOBILE_SELL_EDITOR", 11, 133);
        IMPRESSION_MOBILE_SELL_EDU = new WishAnalyticsEvent("IMPRESSION_MOBILE_SELL_EDU", 12, 134);
        IMPRESSION_MOBILE_REQUEST_GIFT_CARD = new WishAnalyticsEvent("IMPRESSION_MOBILE_REQUEST_GIFT_CARD", 13, 137);
        IMPRESSION_MOBILE_REQUEST_GIFT_CARD_CONFIRM = new WishAnalyticsEvent("IMPRESSION_MOBILE_REQUEST_GIFT_CARD_CONFIRM", 14, 138);
        IMPRESSION_MOBILE_SALE_PARTY = new WishAnalyticsEvent("IMPRESSION_MOBILE_SALE_PARTY", 15, 139);
        IMPRESSION_MOBILE_FACEBOOK_AUTOFILL_TOAST = new WishAnalyticsEvent("IMPRESSION_MOBILE_FACEBOOK_AUTOFILL_TOAST", 16, 157);
        IMPRESSION_MOBILE_FACEBOOK_AUTOFILLED_MSG = new WishAnalyticsEvent("IMPRESSION_MOBILE_FACEBOOK_AUTOFILLED_MSG", 17, 158);
        IMPRESSION_MOBILE_EMAIL_SIGN_UP = new WishAnalyticsEvent("IMPRESSION_MOBILE_EMAIL_SIGN_UP", 18, 159);
        IMPRESSION_MOBILE_EMAIL_LOGIN = new WishAnalyticsEvent("IMPRESSION_MOBILE_EMAIL_LOGIN", 19, 160);
        IMPRESSION_MOBILE_EMAIL_FORGOT_PASSWORD = new WishAnalyticsEvent("IMPRESSION_MOBILE_EMAIL_FORGOT_PASSWORD", 20, 161);
        IMPRESSION_MOBILE_EMAIL_CHANGE_PASSWORD = new WishAnalyticsEvent("IMPRESSION_MOBILE_EMAIL_CHANGE_PASSWORD", 21, 162);
        IMPRESSION_MOBILE_EMAIL_UPDATE_PROFILE = new WishAnalyticsEvent("IMPRESSION_MOBILE_EMAIL_UPDATE_PROFILE", 22, 163);
        IMPRESSION_MOBILE_FEED_ENDED_WIDGET = new WishAnalyticsEvent("IMPRESSION_MOBILE_FEED_ENDED_WIDGET", 23, 164);
        IMPRESSION_MOBILE_FEED_FILTER = new WishAnalyticsEvent("IMPRESSION_MOBILE_FEED_FILTER", 24, 173);
        IMPRESSION_MOBILE_REVIEW_CART = new WishAnalyticsEvent("IMPRESSION_MOBILE_REVIEW_CART", 25, 175);
        IMPRESSION_MOBILE_CHECKOUT_OFFER = new WishAnalyticsEvent("IMPRESSION_MOBILE_CHECKOUT_OFFER", 26, 177);
        IMPRESSION_MOBILE_CREDIT_COUNTER = new WishAnalyticsEvent("IMPRESSION_MOBILE_CREDIT_COUNTER", 27, 178);
        IMPRESSION_MOBILE_CREDIT_BANNER = new WishAnalyticsEvent("IMPRESSION_MOBILE_CREDIT_BANNER", 28, 179);
        IMPRESSION_MOBILE_NATIVE_GIFT_DASHBOARD = new WishAnalyticsEvent("IMPRESSION_MOBILE_NATIVE_GIFT_DASHBOARD", 29, 182);
        IMPRESSION_MOBILE_NATIVE_GIFT_FEED = new WishAnalyticsEvent("IMPRESSION_MOBILE_NATIVE_GIFT_FEED", 30, 183);
        IMPRESSION_MOBILE_NATIVE_GIFT_DETAILS = new WishAnalyticsEvent("IMPRESSION_MOBILE_NATIVE_GIFT_DETAILS", 31, 184);
        IMPRESSION_MOBILE_NATIVE_GIFT_CART = new WishAnalyticsEvent("IMPRESSION_MOBILE_NATIVE_GIFT_CART", 32, 185);
        IMPRESSION_MOBILE_NATIVE_GIFT_EDIT_SHIPPING = new WishAnalyticsEvent("IMPRESSION_MOBILE_NATIVE_GIFT_EDIT_SHIPPING", 33, 186);
        IMPRESSION_MOBILE_NATIVE_GIFT_EDIT_BILLING = new WishAnalyticsEvent("IMPRESSION_MOBILE_NATIVE_GIFT_EDIT_BILLING", 34, 187);
        IMPRESSION_MOBILE_NATIVE_GIFT_COMPLETE = new WishAnalyticsEvent("IMPRESSION_MOBILE_NATIVE_GIFT_COMPLETE", 35, 188);
        IMPRESSION_MOBILE_SIGNUP_GIFT_DASHBOARD = new WishAnalyticsEvent("IMPRESSION_MOBILE_SIGNUP_GIFT_DASHBOARD", 36, 189);
        IMPRESSION_MOBILE_SIGNUP_GIFT_FEED = new WishAnalyticsEvent("IMPRESSION_MOBILE_SIGNUP_GIFT_FEED", 37, 190);
        IMPRESSION_MOBILE_SIGNUP_GIFT_DETAILS = new WishAnalyticsEvent("IMPRESSION_MOBILE_SIGNUP_GIFT_DETAILS", 38, 191);
        IMPRESSION_MOBILE_SIGNUP_GIFT_CART = new WishAnalyticsEvent("IMPRESSION_MOBILE_SIGNUP_GIFT_CART", 39, 192);
        IMPRESSION_MOBILE_SIGNUP_GIFT_EDIT_SHIPPING = new WishAnalyticsEvent("IMPRESSION_MOBILE_SIGNUP_GIFT_EDIT_SHIPPING", 40, 193);
        IMPRESSION_MOBILE_SIGNUP_GIFT_EDIT_BILLING = new WishAnalyticsEvent("IMPRESSION_MOBILE_SIGNUP_GIFT_EDIT_BILLING", 41, 194);
        IMPRESSION_MOBILE_SIGNUP_GIFT_COMPLETE = new WishAnalyticsEvent("IMPRESSION_MOBILE_SIGNUP_GIFT_COMPLETE", 42, 195);
        IMPRESSION_MOBILE_LIVE_SUPPORT_CART = new WishAnalyticsEvent("IMPRESSION_MOBILE_LIVE_SUPPORT_CART", 43, 196);
        IMPRESSION_MOBILE_LIVE_SUPPORT_PROD_DETAILS = new WishAnalyticsEvent("IMPRESSION_MOBILE_LIVE_SUPPORT_PROD_DETAILS", 44, 197);
        IMPRESSION_MOBILE_LIVE_SUPPORT_PENDING = new WishAnalyticsEvent("IMPRESSION_MOBILE_LIVE_SUPPORT_PENDING", 45, 198);
        IMPRESSION_MOBILE_ABANDONED_CART_NOTIFICATION = new WishAnalyticsEvent("IMPRESSION_MOBILE_ABANDONED_CART_NOTIFICATION", 46, 204);
        IMPRESSION_FIRST_LAUNCH = new WishAnalyticsEvent("IMPRESSION_FIRST_LAUNCH", 47, 208);
        IMPRESSION_LOGIN_NOT_FROM_WISH_NOTIFICATION = new WishAnalyticsEvent("IMPRESSION_LOGIN_NOT_FROM_WISH_NOTIFICATION", 48, 211);
        IMPRESSION_MOBILE_NATIVE_MERCHANT_PAGE = new WishAnalyticsEvent("IMPRESSION_MOBILE_NATIVE_MERCHANT_PAGE", 49, 214);
        IMPRESSION_MOBILE_NATIVE_BILLING_ZIP_PAGE = new WishAnalyticsEvent("IMPRESSION_MOBILE_NATIVE_BILLING_ZIP_PAGE", 50, 215);
        IMPRESSION_MOBILE_NATIVE_PRODUCT_RATINGS = new WishAnalyticsEvent("IMPRESSION_MOBILE_NATIVE_PRODUCT_RATINGS", 51, 217);
        IMPRESSION_MOBILE_NATIVE_MERCHANT_RATINGS = new WishAnalyticsEvent("IMPRESSION_MOBILE_NATIVE_MERCHANT_RATINGS", 52, 218);
        IMPRESSION_SIGNUP_NOT_FROM_WISH_NOTIFICATION = new WishAnalyticsEvent("IMPRESSION_SIGNUP_NOT_FROM_WISH_NOTIFICATION", 53, 220);
        IMPRESSION_MOBILE_RATE_TRANSACTION_PROMPT = new WishAnalyticsEvent("IMPRESSION_MOBILE_RATE_TRANSACTION_PROMPT", 54, 221);
        IMPRESSION_MOBILE_SIGNUP_CATEGORY = new WishAnalyticsEvent("IMPRESSION_MOBILE_SIGNUP_CATEGORY", 55, 222);
        IMPRESSION_MOBILE_ADDED_TO_CART_MODAL = new WishAnalyticsEvent("IMPRESSION_MOBILE_ADDED_TO_CART_MODAL", 56, 226);
        IMPRESSION_MOBILE_INVITE_FRIENDS_BY_LINK = new WishAnalyticsEvent("IMPRESSION_MOBILE_INVITE_FRIENDS_BY_LINK", 57, 232);
        IMPRESSION_MOBILE_INVITE_FRIENDS_BY_LINK_PROMPT = new WishAnalyticsEvent("IMPRESSION_MOBILE_INVITE_FRIENDS_BY_LINK_PROMPT", 58, 233);
        IMPRESSION_MY_PROFILE = new WishAnalyticsEvent("IMPRESSION_MY_PROFILE", 59, 246);
        IMPRESSION_OTHER_PROFILE = new WishAnalyticsEvent("IMPRESSION_OTHER_PROFILE", 60, 247);
        IMPRESSION_CROSS_PROMO_BANNER = new WishAnalyticsEvent("IMPRESSION_CROSS_PROMO_BANNER", 61, 255);
        IMPRESSION_CROSS_PROMO_BUY_BLOCKER = new WishAnalyticsEvent("IMPRESSION_CROSS_PROMO_BUY_BLOCKER", 62, 256);
        IMPRESSION_WISH_TO_CART_MODAL = new WishAnalyticsEvent("IMPRESSION_WISH_TO_CART_MODAL", 63, 268);
        IMPRESSION_MOBILE_UPSELL_MODAL = new WishAnalyticsEvent("IMPRESSION_MOBILE_UPSELL_MODAL", 64, 273);
        IMPRESSION_MOBILE_CART_ABANDON_OFFER = new WishAnalyticsEvent("IMPRESSION_MOBILE_CART_ABANDON_OFFER", 65, 286);
        IMPRESSION_MOBILE_FREE_GIFTS_SCREEN = new WishAnalyticsEvent("IMPRESSION_MOBILE_FREE_GIFTS_SCREEN", 66, 287);
        IMPRESSION_MOBILE_FREE_GIFT_ADD_TO_CART_MODAL = new WishAnalyticsEvent("IMPRESSION_MOBILE_FREE_GIFT_ADD_TO_CART_MODAL", 67, 288);
        IMPRESSION_MOBILE_FREE_GIFT_SHIPPING_INFO = new WishAnalyticsEvent("IMPRESSION_MOBILE_FREE_GIFT_SHIPPING_INFO", 68, 289);
        IMPRESSION_MOBILE_FREE_GIFT_SHIPPING_ERROR_MODAL = new WishAnalyticsEvent("IMPRESSION_MOBILE_FREE_GIFT_SHIPPING_ERROR_MODAL", 69, 290);
        IMPRESSION_MOBILE_FREE_GIFT_BILLING_INFO = new WishAnalyticsEvent("IMPRESSION_MOBILE_FREE_GIFT_BILLING_INFO", 70, 291);
        IMPRESSION_MOBILE_FREE_GIFT_BILLING_ERROR_MODAL = new WishAnalyticsEvent("IMPRESSION_MOBILE_FREE_GIFT_BILLING_ERROR_MODAL", 71, 292);
        IMPRESSION_MOBILE_FREE_GIFT_APPLIED_MODAL = new WishAnalyticsEvent("IMPRESSION_MOBILE_FREE_GIFT_APPLIED_MODAL", 72, 293);
        IMPRESSION_MOBILE_SIGNUP_UPDATE_PROFILE = new WishAnalyticsEvent("IMPRESSION_MOBILE_SIGNUP_UPDATE_PROFILE", 73, 294);
        IMPRESSION_MOBILE_GOOGLE_APPINDEXING_WEB_GOOGLE = new WishAnalyticsEvent("IMPRESSION_MOBILE_GOOGLE_APPINDEXING_WEB_GOOGLE", 74, 326);
        IMPRESSION_MOBILE_GOOGLE_APPINDEXING_WEB_OTHER = new WishAnalyticsEvent("IMPRESSION_MOBILE_GOOGLE_APPINDEXING_WEB_OTHER", 75, 327);
        IMPRESSION_MOBILE_GOOGLE_APPINDEXING_APP_GOOGLE = new WishAnalyticsEvent("IMPRESSION_MOBILE_GOOGLE_APPINDEXING_APP_GOOGLE", 76, 328);
        IMPRESSION_MOBILE_GOOGLE_APPINDEXING_APP_OTHER = new WishAnalyticsEvent("IMPRESSION_MOBILE_GOOGLE_APPINDEXING_APP_OTHER", 77, 329);
        IMPRESSION_MOBILE_GOOGLE_APPINDEXING_CRAWLER = new WishAnalyticsEvent("IMPRESSION_MOBILE_GOOGLE_APPINDEXING_CRAWLER", 78, 330);
        IMPRESSION_MOBILE_SIGNUP_INTROGRAPHIC_PAGE_ONE = new WishAnalyticsEvent("IMPRESSION_MOBILE_SIGNUP_INTROGRAPHIC_PAGE_ONE", 79, 333);
        IMPRESSION_MOBILE_SIGNUP_INTROGRAPHIC_PAGE_TWO = new WishAnalyticsEvent("IMPRESSION_MOBILE_SIGNUP_INTROGRAPHIC_PAGE_TWO", 80, 334);
        IMPRESSION_MOBILE_SIGNUP_INTROGRAPHIC_PAGE_THREE = new WishAnalyticsEvent("IMPRESSION_MOBILE_SIGNUP_INTROGRAPHIC_PAGE_THREE", 81, 335);
        IMPRESSION_FREE_GIFTS_ABANDONMENT_MODAL = new WishAnalyticsEvent("IMPRESSION_FREE_GIFTS_ABANDONMENT_MODAL", 82, 336);
        IMPRESSION_DEAL_DASH_START = new WishAnalyticsEvent("IMPRESSION_DEAL_DASH_START", 83, 337);
        IMPRESSION_DEAL_DASH_COUNTDOWN = new WishAnalyticsEvent("IMPRESSION_DEAL_DASH_COUNTDOWN", 84, 338);
        IMPRESSION_DEAL_DASH_FEED = new WishAnalyticsEvent("IMPRESSION_DEAL_DASH_FEED", 85, 339);
        IMPRESSION_DEAL_DASH_WAIT = new WishAnalyticsEvent("IMPRESSION_DEAL_DASH_WAIT", 86, 340);
        IMPRESSION_DEAL_DASH_MODAL = new WishAnalyticsEvent("IMPRESSION_DEAL_DASH_MODAL", 87, 341);
        IMPRESSION_CART_EDUCATION_MODAL = new WishAnalyticsEvent("IMPRESSION_CART_EDUCATION_MODAL", 88, 342);
        CLICK_RELATED_PRODUCT = new WishAnalyticsEvent("CLICK_RELATED_PRODUCT", 89, 1247);
        CLICK_MOBILE_SEARCH = new WishAnalyticsEvent("CLICK_MOBILE_SEARCH", 90, 1309);
        CLICK_MOBILE_SEARCH_HISTORY = new WishAnalyticsEvent("CLICK_MOBILE_SEARCH_HISTORY", 91, 1310);
        CLICK_MOBILE_SEARCH_PRODUCT = new WishAnalyticsEvent("CLICK_MOBILE_SEARCH_PRODUCT", 92, 1311);
        CLICK_MOBILE_SEARCH_FRIEND = new WishAnalyticsEvent("CLICK_MOBILE_SEARCH_FRIEND", 93, 1312);
        CLICK_MOBILE_HOME = new WishAnalyticsEvent("CLICK_MOBILE_HOME", 94, 1328);
        CLICK_MOBILE_SIGNUP_STEP_THREE_NEXT = new WishAnalyticsEvent("CLICK_MOBILE_SIGNUP_STEP_THREE_NEXT", 95, 1347);
        CLICK_MOBILE_SIDE_NAV_PROFILE = new WishAnalyticsEvent("CLICK_MOBILE_SIDE_NAV_PROFILE", 96, 1354);
        CLICK_MOBILE_SIDE_NAV_NOTIFICATIONS = new WishAnalyticsEvent("CLICK_MOBILE_SIDE_NAV_NOTIFICATIONS", 97, 1355);
        CLICK_MOBILE_SIDE_NAV_WALLET = new WishAnalyticsEvent("CLICK_MOBILE_SIDE_NAV_WALLET", 98, 1358);
        CLICK_MOBILE_SIDE_NAV_CART = new WishAnalyticsEvent("CLICK_MOBILE_SIDE_NAV_CART", 99, 1359);
        CLICK_MOBILE_SIDE_NAV_INVITE = new WishAnalyticsEvent("CLICK_MOBILE_SIDE_NAV_INVITE", 100, 1362);
        CLICK_MOBILE_SIDE_NAV_ORDER_HISTORY = new WishAnalyticsEvent("CLICK_MOBILE_SIDE_NAV_ORDER_HISTORY", 101, 1363);
        CLICK_MOBILE_SIDE_NAV_HELP = new WishAnalyticsEvent("CLICK_MOBILE_SIDE_NAV_HELP", 102, 1364);
        CLICK_MOBILE_SIDE_NAV_SETTINGS = new WishAnalyticsEvent("CLICK_MOBILE_SIDE_NAV_SETTINGS", 103, 1365);
        CLICK_MOBILE_NATIVE_CHECKOUT = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_CHECKOUT", 104, 1423);
        CLICK_MOBILE_NATIVE_PLACE_ORDER = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_PLACE_ORDER", 105, 1424);
        CLICK_MOBILE_NATIVE_PLACE_ORDER_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_PLACE_ORDER_SUCCESS", 106, 1425);
        CLICK_MOBILE_NATIVE_PLACE_ORDER_FAILURE = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_PLACE_ORDER_FAILURE", 107, 1426);
        CLICK_MOBILE_NATIVE_PAYPAL_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_PAYPAL_SUCCESS", 108, 1427);
        CLICK_MOBILE_NATIVE_PAYPAL_FAILURE = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_PAYPAL_FAILURE", 109, 1428);
        CLICK_MOBILE_NATIVE_SHIPPING_NEXT = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_SHIPPING_NEXT", 110, 1429);
        CLICK_MOBILE_NATIVE_SHIPPING_NEXT_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_SHIPPING_NEXT_SUCCESS", 111, 1430);
        CLICK_MOBILE_NATIVE_SHIPPING_NEXT_FAILURE = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_SHIPPING_NEXT_FAILURE", 112, 1431);
        CLICK_MOBILE_NATIVE_BILLING_NEXT_PAYPAL = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_NEXT_PAYPAL", 113, 1432);
        CLICK_MOBILE_NATIVE_BILLING_NEXT_CC = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_NEXT_CC", 114, 1433);
        CLICK_MOBILE_NATIVE_BILLING_NEXT_CC_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_NEXT_CC_SUCCESS", 115, 1434);
        CLICK_MOBILE_NATIVE_BILLING_NEXT_CC_FAILURE = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_NEXT_CC_FAILURE", 116, 1435);
        CLICK_MOBILE_NATIVE_BILLING_SCAN = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_SCAN", 117, 1436);
        CLICK_MOBILE_NATIVE_BILLING_SCAN_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_SCAN_SUCCESS", 118, 1437);
        CLICK_MOBILE_NATIVE_EDIT_BILLING = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_EDIT_BILLING", 119, 1438);
        CLICK_MOBILE_NATIVE_EDIT_SHIPPING = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_EDIT_SHIPPING", 120, 1439);
        CLICK_MOBILE_NATIVE_EDIT_BILLING_EMPTY = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_EDIT_BILLING_EMPTY", 121, 1440);
        CLICK_MOBILE_NATIVE_EDIT_SHIPPING_EMPTY = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_EDIT_SHIPPING_EMPTY", 122, 1441);
        CLICK_MOBILE_WALLET_ITEM = new WishAnalyticsEvent("CLICK_MOBILE_WALLET_ITEM", 123, 1442);
        CLICK_MOBILE_NATIVE_AUTO_PLACE_ORDER = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_AUTO_PLACE_ORDER", 124, 1443);
        CLICK_MOBILE_NATIVE_AUTO_PLACE_ORDER_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_AUTO_PLACE_ORDER_SUCCESS", 125, 1444);
        CLICK_MOBILE_NATIVE_AUTO_PLACE_ORDER_FAILURE = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_AUTO_PLACE_ORDER_FAILURE", 126, 1445);
        CLICK_MOBILE_SIDE_NAV_SELL = new WishAnalyticsEvent("CLICK_MOBILE_SIDE_NAV_SELL", 127, 1446);
        CLICK_MOBILE_SELL_EDU_LEARN = new WishAnalyticsEvent("CLICK_MOBILE_SELL_EDU_LEARN", 128, 1447);
        CLICK_MOBILE_SELL_EDU_SKIP = new WishAnalyticsEvent("CLICK_MOBILE_SELL_EDU_SKIP", 129, 1448);
        CLICK_MOBILE_SELL_EDU_CHANGE_PAGE = new WishAnalyticsEvent("CLICK_MOBILE_SELL_EDU_CHANGE_PAGE", 130, 1449);
        CLICK_MOBILE_SELL_EDU_GET_STARTED = new WishAnalyticsEvent("CLICK_MOBILE_SELL_EDU_GET_STARTED", 131, 1450);
        CLICK_MOBILE_SELL_CAMERA_TAKE_PIC = new WishAnalyticsEvent("CLICK_MOBILE_SELL_CAMERA_TAKE_PIC", 132, 1451);
        CLICK_MOBILE_SELL_CAMERA_GALLERY = new WishAnalyticsEvent("CLICK_MOBILE_SELL_CAMERA_GALLERY", 133, 1452);
        CLICK_MOBILE_SELL_IMAGE_CONFIRM = new WishAnalyticsEvent("CLICK_MOBILE_SELL_IMAGE_CONFIRM", 134, 1453);
        CLICK_MOBILE_SELL_IMAGE_CANCEL = new WishAnalyticsEvent("CLICK_MOBILE_SELL_IMAGE_CANCEL", 135, 1454);
        CLICK_MOBILE_SELL_ADD_EXTRA_PHOTO = new WishAnalyticsEvent("CLICK_MOBILE_SELL_ADD_EXTRA_PHOTO", 136, 1455);
        CLICK_MOBILE_SELL_CANCEL = new WishAnalyticsEvent("CLICK_MOBILE_SELL_CANCEL", 137, 1456);
        CLICK_MOBILE_SELL_SUBMIT = new WishAnalyticsEvent("CLICK_MOBILE_SELL_SUBMIT", 138, 1457);
        CLICK_MOBILE_REQUEST_GIFT_CARD = new WishAnalyticsEvent("CLICK_MOBILE_REQUEST_GIFT_CARD", 139, 1462);
        CLICK_MOBILE_REQUEST_GIFT_CARD_CONFIRM = new WishAnalyticsEvent("CLICK_MOBILE_REQUEST_GIFT_CARD_CONFIRM", 140, 1463);
        CLICK_MOBILE_SALE_PARTY_SELL = new WishAnalyticsEvent("CLICK_MOBILE_SALE_PARTY_SELL", 141, 1464);
        CLICK_MOBILE_SALE_PARTY_SHOP = new WishAnalyticsEvent("CLICK_MOBILE_SALE_PARTY_SHOP", 142, 1465);
        CLICK_MOBILE_SIDE_NAV_SALE_PARTY = new WishAnalyticsEvent("CLICK_MOBILE_SIDE_NAV_SALE_PARTY", 143, 1466);
        CLICK_GIFT_GIFT_IT_BUTTON = new WishAnalyticsEvent("CLICK_GIFT_GIFT_IT_BUTTON", 144, 1469);
        CLICK_MOBILE_SIDE_NAV_UPCOMMING_BIRTHDAY = new WishAnalyticsEvent("CLICK_MOBILE_SIDE_NAV_UPCOMMING_BIRTHDAY", 145, 1493);
        CLICK_MOBILE_SHIPPING_AUTOFILL_TOAST = new WishAnalyticsEvent("CLICK_MOBILE_SHIPPING_AUTOFILL_TOAST", 146, 1494);
        CLICK_MOBILE_SHIPPING_AUTOFILL_TOAST_MIN = new WishAnalyticsEvent("CLICK_MOBILE_SHIPPING_AUTOFILL_TOAST_MIN", 147, 1495);
        CLICK_MOBILE_SHIPPING_AUTOFILL_TOAST_SUC = new WishAnalyticsEvent("CLICK_MOBILE_SHIPPING_AUTOFILL_TOAST_SUC", 148, 1496);
        CLICK_MOBILE_BILLING_AUTOFILL_TOAST = new WishAnalyticsEvent("CLICK_MOBILE_BILLING_AUTOFILL_TOAST", 149, 1497);
        CLICK_MOBILE_BILLING_AUTOFILL_TOAST_MIN = new WishAnalyticsEvent("CLICK_MOBILE_BILLING_AUTOFILL_TOAST_MIN", 150, 1498);
        CLICK_MOBILE_BILLING_AUTOFILL_TOAST_SUC = new WishAnalyticsEvent("CLICK_MOBILE_BILLING_AUTOFILL_TOAST_SUC", 151, 1499);
        CLICK_MOBILE_BILLING_AUTOFILL_DISMISS = new WishAnalyticsEvent("CLICK_MOBILE_BILLING_AUTOFILL_DISMISS", 152, 1500);
        CLICK_MOBILE_NATIVE_BILLING_NEXT_FACEBOOK = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_NEXT_FACEBOOK", 153, 1501);
        CLICK_MOBILE_NATIVE_PAYPAL_ORDER = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_PAYPAL_ORDER", 154, 1502);
        CLICK_MOBILE_NATIVE_FACEBOOK_ORDER = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_FACEBOOK_ORDER", 155, 1503);
        CLICK_MOBILE_NATIVE_FACEBOOK_ORDER_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_FACEBOOK_ORDER_SUCCESS", 156, 1504);
        CLICK_MOBILE_NATIVE_FACEBOOK_ORDER_FAILURE = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_FACEBOOK_ORDER_FAILURE", 157, 1505);
        CLICK_MOBILE_SPLASH_EMAIL_SIGN_UP = new WishAnalyticsEvent("CLICK_MOBILE_SPLASH_EMAIL_SIGN_UP", 158, 1506);
        CLICK_MOBILE_SPLASH_EMAIL_LOGIN = new WishAnalyticsEvent("CLICK_MOBILE_SPLASH_EMAIL_LOGIN", 159, 1507);
        CLICK_MOBILE_EMAIL_SIGN_UP = new WishAnalyticsEvent("CLICK_MOBILE_EMAIL_SIGN_UP", 160, 1508);
        CLICK_MOBILE_EMAIL_FORGOT_PASSWORD = new WishAnalyticsEvent("CLICK_MOBILE_EMAIL_FORGOT_PASSWORD", 161, 1509);
        CLICK_MOBILE_EMAIL_LOGIN = new WishAnalyticsEvent("CLICK_MOBILE_EMAIL_LOGIN", 162, 1510);
        CLICK_MOBILE_EMAIL_UPDATE_PROFILE_NEXT = new WishAnalyticsEvent("CLICK_MOBILE_EMAIL_UPDATE_PROFILE_NEXT", 163, 1511);
        CLICK_MOBILE_EMAIL_UPDATE_PROFILE_SKIP = new WishAnalyticsEvent("CLICK_MOBILE_EMAIL_UPDATE_PROFILE_SKIP", 164, 1512);
        CLICK_MOBILE_EMAIL_CHANGE_PASSWORD = new WishAnalyticsEvent("CLICK_MOBILE_EMAIL_CHANGE_PASSWORD", 165, 1513);
        CLICK_MOBILE_NATIVE_PAYPAL_AUTO_ORDER = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_PAYPAL_AUTO_ORDER", 166, 1514);
        CLICK_MOBILE_NATIVE_FACEBOOK_AUTO_ORDER = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_FACEBOOK_AUTO_ORDER", 167, 1515);
        CLICK_MOBILE_FEED_ENDED_WIDGET = new WishAnalyticsEvent("CLICK_MOBILE_FEED_ENDED_WIDGET", 168, 1516);
        CLICK_MOBILE_SPLASH_FACEBOOK_LOGIN = new WishAnalyticsEvent("CLICK_MOBILE_SPLASH_FACEBOOK_LOGIN", 169, 1517);
        CLICK_MOBILE_SORT_MODE = new WishAnalyticsEvent("CLICK_MOBILE_SORT_MODE", 170, 1520);
        CLICK_MOBILE_DEEP_LINK_SORT_MODE = new WishAnalyticsEvent("CLICK_MOBILE_DEEP_LINK_SORT_MODE", 171, 1522);
        CLICK_MOBILE_SIDE_NAV_SEARCH = new WishAnalyticsEvent("CLICK_MOBILE_SIDE_NAV_SEARCH", 172, 1527);
        CLICK_MOBILE_SEARCH_POPULAR = new WishAnalyticsEvent("CLICK_MOBILE_SEARCH_POPULAR", 173, 1528);
        CLICK_MOBILE_NATIVE_GWALLET_CHANGE_SHIPPING = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_GWALLET_CHANGE_SHIPPING", 174, 1532);
        CLICK_MOBILE_NATIVE_BUY_WITH_GOOGLE = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BUY_WITH_GOOGLE", 175, 1533);
        CLICK_MOBILE_NATIVE_GWALLET_FETCH = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_GWALLET_FETCH", 176, 1534);
        CLICK_MOBILE_NATIVE_GWALLET_FETCH_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_GWALLET_FETCH_SUCCESS", 177, 1535);
        CLICK_MOBILE_NATIVE_GWALLET_FETCH_FAILURE = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_GWALLET_FETCH_FAILURE", 178, 1536);
        CLICK_MOBILE_NATIVE_BILLING_NEXT_GWALLET = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_NEXT_GWALLET", 179, 1537);
        CLICK_MOBILE_NATIVE_GWALLET_FULL_FETCH = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_GWALLET_FULL_FETCH", 180, 1538);
        CLICK_MOBILE_NATIVE_GWALLET_FULL_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_GWALLET_FULL_SUCCESS", 181, 1539);
        CLICK_MOBILE_NATIVE_GWALLET_FULL_FAILURE = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_GWALLET_FULL_FAILURE", 182, 1540);
        CLICK_MOBILE_NATIVE_GWALLET_ORDER = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_GWALLET_ORDER", 183, 1541);
        CLICK_MOBILE_NATIVE_GWALLET_ORDER_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_GWALLET_ORDER_SUCCESS", 184, 1542);
        CLICK_MOBILE_NATIVE_GWALLET_ORDER_FAILURE = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_GWALLET_ORDER_FAILURE", 185, 1543);
        CLICK_MOBILE_CHOME_CATEGORY = new WishAnalyticsEvent("CLICK_MOBILE_CHOME_CATEGORY", 186, 1546);
        CLICK_MOBILE_CHOME_COLLECTION = new WishAnalyticsEvent("CLICK_MOBILE_CHOME_COLLECTION", 187, 1547);
        CLICK_MOBILE_SIGNUP_GIFTING_SKIP = new WishAnalyticsEvent("CLICK_MOBILE_SIGNUP_GIFTING_SKIP", 188, 1549);
        CLICK_MOBILE_GIFTING_DASH_SLIDER_FEED = new WishAnalyticsEvent("CLICK_MOBILE_GIFTING_DASH_SLIDER_FEED", 189, 1550);
        CLICK_MOBILE_GIFTING_DASH_FRIEND_FEED = new WishAnalyticsEvent("CLICK_MOBILE_GIFTING_DASH_FRIEND_FEED", 190, 1551);
        CLICK_MOBILE_GIFTING_DASH_FB_LOGIN = new WishAnalyticsEvent("CLICK_MOBILE_GIFTING_DASH_FB_LOGIN", 191, 1552);
        CLICK_MOBILE_GIFTING_DASH_COLLECTION = new WishAnalyticsEvent("CLICK_MOBILE_GIFTING_DASH_COLLECTION", 192, 1553);
        CLICK_MOBILE_GIFTING_BUY_MORE_GIFTS = new WishAnalyticsEvent("CLICK_MOBILE_GIFTING_BUY_MORE_GIFTS", 193, 1554);
        CLICK_MOBILE_GIFTING_DONE_BUYING_GIFTS = new WishAnalyticsEvent("CLICK_MOBILE_GIFTING_DONE_BUYING_GIFTS", 194, 1555);
        CLICK_MOBILE_GIFTING_EDIT_SHIPPING = new WishAnalyticsEvent("CLICK_MOBILE_GIFTING_EDIT_SHIPPING", 195, 1556);
        CLICK_MOBILE_GIFTING_EDIT_BILLING = new WishAnalyticsEvent("CLICK_MOBILE_GIFTING_EDIT_BILLING", 196, 1557);
        CLICK_MOBILE_GIFTING_PLACE_ORDER = new WishAnalyticsEvent("CLICK_MOBILE_GIFTING_PLACE_ORDER", 197, 1558);
        CLICK_MOBILE_GIFTING_PLACE_ORDER_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_GIFTING_PLACE_ORDER_SUCCESS", 198, 1559);
        CLICK_MOBILE_GIFTING_PLACE_ORDER_FAILURE = new WishAnalyticsEvent("CLICK_MOBILE_GIFTING_PLACE_ORDER_FAILURE", 199, 1560);
        CLICK_MOBILE_GIFTING_DASH_FRIEND_FACE = new WishAnalyticsEvent("CLICK_MOBILE_GIFTING_DASH_FRIEND_FACE", 200, 1561);
        CLICK_MOBILE_GIFTING_NATIVE_CHECKOUT = new WishAnalyticsEvent("CLICK_MOBILE_GIFTING_NATIVE_CHECKOUT", 201, 1562);
        CLICK_MOBILE_LIVE_SUPPORT_CART = new WishAnalyticsEvent("CLICK_MOBILE_LIVE_SUPPORT_CART", 202, 1563);
        CLICK_MOBILE_LIVE_SUPPORT_PROD_DETAILS = new WishAnalyticsEvent("CLICK_MOBILE_LIVE_SUPPORT_PROD_DETAILS", 203, 1564);
        CLICK_MOBILE_LIVE_SUPPORT_PENDING = new WishAnalyticsEvent("CLICK_MOBILE_LIVE_SUPPORT_PENDING", 204, 1565);
        CLICK_MOBILE_ABANDONED_CART_NOTIFICATION = new WishAnalyticsEvent("CLICK_MOBILE_ABANDONED_CART_NOTIFICATION", 205, 1568);
        CLICK_MOBILE_NATIVE_PAYPAL_CANCEL = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_PAYPAL_CANCEL", 206, 1569);
        CLICK_MOBILE_NATIVE_PAYPAL_PAY_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_PAYPAL_PAY_SUCCESS", 207, 1570);
        CLICK_MOBILE_NATIVE_PAYPAL_PAY_ERROR = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_PAYPAL_PAY_ERROR", 208, 1571);
        CLICK_MOBILE_NATIVE_PAYPAL_PREPAY_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_PAYPAL_PREPAY_SUCCESS", 209, 1572);
        CLICK_MOBILE_NATIVE_PAYPAL_PREPAY_ERROR = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_PAYPAL_PREPAY_ERROR", 210, 1573);
        CLICK_MOBILE_NATIVE_PAYPAL_VERIFY_ERROR = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_PAYPAL_VERIFY_ERROR", 211, 1574);
        CLICK_MOBILE_NATIVE_PAYPAL_VERIFY_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_PAYPAL_VERIFY_SUCCESS", 212, 1575);
        CLICK_MOBILE_EXTRA_PHOTOS = new WishAnalyticsEvent("CLICK_MOBILE_EXTRA_PHOTOS", 213, 1580);
        CLICK_MOBILE_FEED_EXTRA_PHOTOS = new WishAnalyticsEvent("CLICK_MOBILE_FEED_EXTRA_PHOTOS", 214, 1581);
        CLICK_MOBILE_NATIVE_MERCHANT_CHANGE_TAB = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_MERCHANT_CHANGE_TAB", 215, 1584);
        CLICK_MOBILE_NATIVE_MERCHANT_VIEW_RATING = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_MERCHANT_VIEW_RATING", 216, 1585);
        CLICK_MOBILE_NATIVE_BILLING_ZIP_NEXT = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_ZIP_NEXT", 217, 1586);
        CLICK_MOBILE_DETAILS_MERCHANT_STORE = new WishAnalyticsEvent("CLICK_MOBILE_DETAILS_MERCHANT_STORE", 218, 1587);
        CLICK_MOBILE_DETAILS_MERCHANT_RATING = new WishAnalyticsEvent("CLICK_MOBILE_DETAILS_MERCHANT_RATING", 219, 1588);
        CLICK_MOBILE_DETAILS_PRODUCT_RATING = new WishAnalyticsEvent("CLICK_MOBILE_DETAILS_PRODUCT_RATING", 220, 1589);
        CLICK_MOBILE_DETAILS_CHANGE_RELATED_TAB = new WishAnalyticsEvent("CLICK_MOBILE_DETAILS_CHANGE_RELATED_TAB", 221, 1590);
        CLICK_MOBILE_RATINGS_VIEW_PRODUCT = new WishAnalyticsEvent("CLICK_MOBILE_RATINGS_VIEW_PRODUCT", 222, 1592);
        CLICK_MOBILE_RATINGS_VISIT_STORE = new WishAnalyticsEvent("CLICK_MOBILE_RATINGS_VISIT_STORE", 223, 1593);
        CLICK_MOBILE_SIGNUP_CATEGORY_NEXT = new WishAnalyticsEvent("CLICK_MOBILE_SIGNUP_CATEGORY_NEXT", 224, 1600);
        CLICK_MOBILE_ADDED_TO_CART_MODAL_SHOP = new WishAnalyticsEvent("CLICK_MOBILE_ADDED_TO_CART_MODAL_SHOP", 225, 1602);
        CLICK_MOBILE_ADDED_TO_CART_MODAL_VIEW_CART = new WishAnalyticsEvent("CLICK_MOBILE_ADDED_TO_CART_MODAL_VIEW_CART", 226, 1605);
        CLICK_MOBILE_NATIVE_BILLING_CC_TAB = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_CC_TAB", 227, 1623);
        CLICK_MOBILE_NATIVE_BILLING_GWALLET_TAB = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_GWALLET_TAB", 228, 1624);
        CLICK_MOBILE_NATIVE_BILLING_PAYPAL_TAB = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_PAYPAL_TAB", 229, 1625);
        CLICK_MOBILE_NATIVE_COLLECTION = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_COLLECTION", 230, 1626);
        CLICK_MOBILE_NATIVE_CATEGORY = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_CATEGORY", 231, 1627);
        CLICK_MOBILE_NATIVE_FOOTER_COLLECTION = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_FOOTER_COLLECTION", 232, 1628);
        CLICK_MOBILE_NATIVE_CATEGORY_START_SCROLL = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_CATEGORY_START_SCROLL", 233, 1631);
        CLICK_MOBILE_NATIVE_CATEGORY_END_SCROLL = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_CATEGORY_END_SCROLL", 234, 1632);
        CLICK_MOBILE_NATIVE_COLLECTION_START_SCROLL = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_COLLECTION_START_SCROLL", 235, 1633);
        CLICK_MOBILE_NATIVE_COLLECTION_END_SCROLL = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_COLLECTION_END_SCROLL", 236, 1634);
        CLICK_MOBILE_NATIVE_SIZING_CHART = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_SIZING_CHART", 237, 1635);
        CLICK_MOBILE_NATIVE_FOOTER_COLLECTION_START_SCROLL = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_FOOTER_COLLECTION_START_SCROLL", 238, 1636);
        CLICK_MOBILE_NATIVE_FOOTER_COLLECTION_END_SCROLL = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_FOOTER_COLLECTION_END_SCROLL", 239, 1637);
        CLICK_MOBILE_INVITE_BY_LINK_EMAIL = new WishAnalyticsEvent("CLICK_MOBILE_INVITE_BY_LINK_EMAIL", 240, 1638);
        CLICK_MOBILE_INVITE_BY_LINK_SMS = new WishAnalyticsEvent("CLICK_MOBILE_INVITE_BY_LINK_SMS", 241, 1639);
        CLICK_MOBILE_INVITE_BY_LINK_SHARE = new WishAnalyticsEvent("CLICK_MOBILE_INVITE_BY_LINK_SHARE", 242, 1640);
        CLICK_MOBILE_INVITE_BY_LINK_DONE = new WishAnalyticsEvent("CLICK_MOBILE_INVITE_BY_LINK_DONE", 243, 1641);
        CLICK_MOBILE_INVITE_BY_LINK_PROMPT_EMAIL = new WishAnalyticsEvent("CLICK_MOBILE_INVITE_BY_LINK_PROMPT_EMAIL", 244, 1642);
        CLICK_MOBILE_INVITE_BY_LINK_PROMPT_SMS = new WishAnalyticsEvent("CLICK_MOBILE_INVITE_BY_LINK_PROMPT_SMS", 245, 1643);
        CLICK_MOBILE_INVITE_BY_LINK_PROMPT_SHARE = new WishAnalyticsEvent("CLICK_MOBILE_INVITE_BY_LINK_PROMPT_SHARE", 246, 1644);
        CLICK_MOBILE_INVITE_BY_LINK_PROMPT_DONE = new WishAnalyticsEvent("CLICK_MOBILE_INVITE_BY_LINK_PROMPT_DONE", 247, 1645);
        CLICK_MOBILE_DETAILS_VIEW_DESCRIPTION = new WishAnalyticsEvent("CLICK_MOBILE_DETAILS_VIEW_DESCRIPTION", 248, 1655);
        CLICK_MOBILE_ZOOM_PRODUCT_PHOTO = new WishAnalyticsEvent("CLICK_MOBILE_ZOOM_PRODUCT_PHOTO", 249, 1662);
        CLICK_RATING_PHOTO = new WishAnalyticsEvent("CLICK_RATING_PHOTO", 250, 1663);
        CLICK_SCROLL_MAIN_PRODUCT_IMAGE = new WishAnalyticsEvent("CLICK_SCROLL_MAIN_PRODUCT_IMAGE", 251, 1664);
        CLICK_MOBILE_DETAILS_GET_CREDIT = new WishAnalyticsEvent("CLICK_MOBILE_DETAILS_GET_CREDIT", 252, 1665);
        CLICK_MOBILE_CART_GET_CREDIT = new WishAnalyticsEvent("CLICK_MOBILE_CART_GET_CREDIT", 253, 1666);
        CLICK_MOBILE_DETAILS_SEARCH = new WishAnalyticsEvent("CLICK_MOBILE_DETAILS_SEARCH", 254, 1669);
        CLICK_MOBILE_NATIVE_BILLING_VISA_TAB = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_VISA_TAB", 255, 1677);
        CLICK_MOBILE_NATIVE_BILLING_SAVE_VISA = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_SAVE_VISA", 256, 1678);
        CLICK_MOBILE_NATIVE_BILLING_SAVE_VISA_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_SAVE_VISA_SUCCESS", 257, 1679);
        CLICK_MOBILE_NATIVE_BILLING_SAVE_VISA_FAILURE = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_SAVE_VISA_FAILURE", 258, 1680);
        CLICK_MOBILE_NATIVE_BILLING_VISA_FETCHED = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_VISA_FETCHED", 259, 1681);
        CLICK_MOBILE_NATIVE_BILLING_VISA_CANCEL = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_VISA_CANCEL", 260, 1682);
        CLICK_MOBILE_NATIVE_BILLING_VISA_ERROR = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_VISA_ERROR", 261, 1683);
        CLICK_MOBILE_NATIVE_BILLING_VISA_START = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_VISA_START", 262, 1684);
        CLICK_MOBILE_RECOMMEND = new WishAnalyticsEvent("CLICK_MOBILE_RECOMMEND", 263, 1687);
        CLICK_MOBILE_ADD_TO_CART_CANCEL = new WishAnalyticsEvent("CLICK_MOBILE_ADD_TO_CART_CANCEL", 264, 1704);
        CLICK_MOBILE_ADD_TO_CART_BUY = new WishAnalyticsEvent("CLICK_MOBILE_ADD_TO_CART_BUY", 265, 1705);
        CLICK_MOBILE_CART_ITEM_CHANGE = new WishAnalyticsEvent("CLICK_MOBILE_CART_ITEM_CHANGE", 266, 1706);
        CLICK_MOBILE_FEED_FILTER_REMOVE = new WishAnalyticsEvent("CLICK_MOBILE_FEED_FILTER_REMOVE", 267, 1707);
        CLICK_MOBILE_FEED_FILTER_NAV = new WishAnalyticsEvent("CLICK_MOBILE_FEED_FILTER_NAV", 268, 1708);
        CLICK_MOBILE_FEED_FILTER_SELECT = new WishAnalyticsEvent("CLICK_MOBILE_FEED_FILTER_SELECT", 269, 1709);
        CLICK_MOBILE_FEED_FILTER_APPLY = new WishAnalyticsEvent("CLICK_MOBILE_FEED_FILTER_APPLY", 270, 1710);
        CLICK_MOBILE_FEED_FILTER_CANCEL = new WishAnalyticsEvent("CLICK_MOBILE_FEED_FILTER_CANCEL", 271, 1711);
        CLICK_MOBILE_FEED_FILTER_SEARCH = new WishAnalyticsEvent("CLICK_MOBILE_FEED_FILTER_SEARCH", 272, 1712);
        CLICK_MOBILE_PRODUCT_DETAIL_SECTION = new WishAnalyticsEvent("CLICK_MOBILE_PRODUCT_DETAIL_SECTION", 273, 1715);
        CLICK_MOBILE_NATIVE_PAYPAL_FUTURE_PAY_ERROR = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_PAYPAL_FUTURE_PAY_ERROR", 274, 1717);
        CLICK_MOBILE_NATIVE_PAYPAL_FUTURE_PAY_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_PAYPAL_FUTURE_PAY_SUCCESS", 275, 1718);
        CLICK_MOBILE_NATIVE_PAYPAL_AUTH_ERROR = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_PAYPAL_AUTH_ERROR", 276, 1719);
        CLICK_MOBILE_NATIVE_PAYPAL_AUTH_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_PAYPAL_AUTH_SUCCESS", 277, 1720);
        CLICK_WISH_TO_CART_MODAL_BUY = new WishAnalyticsEvent("CLICK_WISH_TO_CART_MODAL_BUY", 278, 1721);
        CLICK_WISH_TO_CART_MODAL_CANCEL = new WishAnalyticsEvent("CLICK_WISH_TO_CART_MODAL_CANCEL", 279, 1722);
        CLICK_MOBILE_SIGNUP_EMAIL_SUGGEST = new WishAnalyticsEvent("CLICK_MOBILE_SIGNUP_EMAIL_SUGGEST", 280, 1726);
        CLICK_MOBILE_SIGNUP_EMAIL_CONFIRM_FAIL = new WishAnalyticsEvent("CLICK_MOBILE_SIGNUP_EMAIL_CONFIRM_FAIL", 281, 1727);
        CLICK_MOBILE_SIGNUP_VIEW_WITH_NONE = new WishAnalyticsEvent("CLICK_MOBILE_SIGNUP_VIEW_WITH_NONE", 282, 1728);
        CLICK_MOBILE_SIGNUP_VIEW_WITH_CONFIRM = new WishAnalyticsEvent("CLICK_MOBILE_SIGNUP_VIEW_WITH_CONFIRM", 283, 1729);
        CLICK_MOBILE_SIGNUP_VIEW_WITH_SUGGEST = new WishAnalyticsEvent("CLICK_MOBILE_SIGNUP_VIEW_WITH_SUGGEST", 284, 1730);
        CLICK_MOBILE_SIGNUP_VIEW_WITH_BOTH = new WishAnalyticsEvent("CLICK_MOBILE_SIGNUP_VIEW_WITH_BOTH", 285, 1731);
        CLICK_MOBILE_SIGNUP_SUCCESS_WITH_NONE = new WishAnalyticsEvent("CLICK_MOBILE_SIGNUP_SUCCESS_WITH_NONE", 286, 1732);
        CLICK_MOBILE_SIGNUP_SUCCESS_WITH_CONFIRM = new WishAnalyticsEvent("CLICK_MOBILE_SIGNUP_SUCCESS_WITH_CONFIRM", 287, 1733);
        CLICK_MOBILE_SIGNUP_SUCCESS_WITH_SUGGEST = new WishAnalyticsEvent("CLICK_MOBILE_SIGNUP_SUCCESS_WITH_SUGGEST", 288, 1734);
        CLICK_MOBILE_SIGNUP_SUCCESS_WITH_BOTH = new WishAnalyticsEvent("CLICK_MOBILE_SIGNUP_SUCCESS_WITH_BOTH", 289, 1735);
        CLICK_MOBILE_CART_CONTINUE_SHOPPING = new WishAnalyticsEvent("CLICK_MOBILE_CART_CONTINUE_SHOPPING", 290, 1743);
        CLICK_MOBILE_UPSELL_MODAL_BUY_BUTTON = new WishAnalyticsEvent("CLICK_MOBILE_UPSELL_MODAL_BUY_BUTTON", 291, 1750);
        CLICK_MOBILE_UPSELL_MODAL_PRODUCT_SCROLL = new WishAnalyticsEvent("CLICK_MOBILE_UPSELL_MODAL_PRODUCT_SCROLL", 292, 1751);
        CLICK_MOBILE_UPSELL_MODAL_NO_THANKS_BUTTON = new WishAnalyticsEvent("CLICK_MOBILE_UPSELL_MODAL_NO_THANKS_BUTTON", 293, 1752);
        CLICK_MOBILE_FREE_GIFT_CLAIM_BUTTON = new WishAnalyticsEvent("CLICK_MOBILE_FREE_GIFT_CLAIM_BUTTON", 294, 1755);
        CLICK_MOBILE_FREE_GIFT_CLAIM_CANCEL_BUTTON = new WishAnalyticsEvent("CLICK_MOBILE_FREE_GIFT_CLAIM_CANCEL_BUTTON", 295, 1756);
        CLICK_MOBILE_FREE_GIFT_SCROLL_PRODUCT = new WishAnalyticsEvent("CLICK_MOBILE_FREE_GIFT_SCROLL_PRODUCT", 296, 1757);
        CLICK_MOBILE_FREE_GIFT_SHIPPING_SAME_AS_CHECKBOX = new WishAnalyticsEvent("CLICK_MOBILE_FREE_GIFT_SHIPPING_SAME_AS_CHECKBOX", 297, 1758);
        CLICK_MOBILE_FREE_GIFT_SHIPPING_NEXT_BUTTON = new WishAnalyticsEvent("CLICK_MOBILE_FREE_GIFT_SHIPPING_NEXT_BUTTON", 298, 1759);
        CLICK_MOBILE_FREE_GIFT_SHIPPING_CANCEL_BUTTON = new WishAnalyticsEvent("CLICK_MOBILE_FREE_GIFT_SHIPPING_CANCEL_BUTTON", 299, 1760);
        CLICK_MOBILE_FREE_GIFT_BILLING_REDEEM_BUTTON = new WishAnalyticsEvent("CLICK_MOBILE_FREE_GIFT_BILLING_REDEEM_BUTTON", 300, 1761);
        CLICK_MOBILE_FREE_GIFT_BILLING_CANCEL_BUTTON = new WishAnalyticsEvent("CLICK_MOBILE_FREE_GIFT_BILLING_CANCEL_BUTTON", 301, 1762);
        CLICK_MOBILE_FREE_GIFT_APPLIED_MODAL_CONTINUE = new WishAnalyticsEvent("CLICK_MOBILE_FREE_GIFT_APPLIED_MODAL_CONTINUE", 302, 1763);
        CLICK_MOBILE_FREE_GIFT_SHIPPING_BACK_BUTTON = new WishAnalyticsEvent("CLICK_MOBILE_FREE_GIFT_SHIPPING_BACK_BUTTON", 303, 1764);
        CLICK_MOBILE_FREE_GIFT_BILLING_BACK_BUTTON = new WishAnalyticsEvent("CLICK_MOBILE_FREE_GIFT_BILLING_BACK_BUTTON", 304, 1765);
        CLICK_MOBILE_FREE_GIFT_ADD_TO_CART_MODAL_CANCEL = new WishAnalyticsEvent("CLICK_MOBILE_FREE_GIFT_ADD_TO_CART_MODAL_CANCEL", 305, 1766);
        CLICK_MOBILE_FREE_GIFT_ADD_TO_CART_MODAL_BUY = new WishAnalyticsEvent("CLICK_MOBILE_FREE_GIFT_ADD_TO_CART_MODAL_BUY", 306, 1767);
        CLICK_MOBILE_SIGNUP_UPDATE_PROFILE_NEXT = new WishAnalyticsEvent("CLICK_MOBILE_SIGNUP_UPDATE_PROFILE_NEXT", 307, 1768);
        CLICK_MOBILE_SIGNUP_UPDATE_PROFILE_SKIP = new WishAnalyticsEvent("CLICK_MOBILE_SIGNUP_UPDATE_PROFILE_SKIP", 308, 1769);
        CLICK_MOBILE_NATIVE_BILLING_OXXO_TAB = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_OXXO_TAB", 309, 1770);
        CLICK_MOBILE_NATIVE_BILLING_NEXT_OXXO = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_NEXT_OXXO", 310, 1771);
        CLICK_MOBILE_NATIVE_BILLING_NEXT_OXXO_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_NEXT_OXXO_SUCCESS", 311, 1772);
        CLICK_MOBILE_NATIVE_BILLING_NEXT_OXXO_FAILURE = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_NEXT_OXXO_FAILURE", 312, 1773);
        CLICK_MOBILE_NATIVE_OXXO_PLACE_ORDER = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_OXXO_PLACE_ORDER", 313, 1774);
        CLICK_MOBILE_NATIVE_OXXO_PLACE_ORDER_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_OXXO_PLACE_ORDER_SUCCESS", 314, 1775);
        CLICK_MOBILE_NATIVE_OXXO_PLACE_ORDER_FAILURE = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_OXXO_PLACE_ORDER_FAILURE", 315, 1776);
        CLICK_MOBILE_SIDE_FAQ = new WishAnalyticsEvent("CLICK_MOBILE_SIDE_FAQ", 316, 1836);
        CLICK_MOBILE_SIGNUP_INTROGRAPHIC_NEXT = new WishAnalyticsEvent("CLICK_MOBILE_SIGNUP_INTROGRAPHIC_NEXT", 317, 1857);
        CLICK_MOBILE_SIGNUP_INTROGRAPHIC_SKIP = new WishAnalyticsEvent("CLICK_MOBILE_SIGNUP_INTROGRAPHIC_SKIP", 318, 1858);
        CLICK_MOBILE_FREE_GIFT_ABANDONMENT_MODAL_PROCEED = new WishAnalyticsEvent("CLICK_MOBILE_FREE_GIFT_ABANDONMENT_MODAL_PROCEED", 319, 1859);
        CLICK_MOBILE_FREE_GIFT_ABANDONMENT_MODAL_RETURN = new WishAnalyticsEvent("CLICK_MOBILE_FREE_GIFT_ABANDONMENT_MODAL_RETURN", 320, 1860);
        CLICK_DEAL_DASH_TAB = new WishAnalyticsEvent("CLICK_DEAL_DASH_TAB", 321, 1861);
        CLICK_DEAL_DASH_START = new WishAnalyticsEvent("CLICK_DEAL_DASH_START", 322, 1862);
        CLICK_DEAL_DASH_LEAVE = new WishAnalyticsEvent("CLICK_DEAL_DASH_LEAVE", 323, 1863);
        CLICK_DEAL_DASH_GO_TO_CART_MODAL = new WishAnalyticsEvent("CLICK_DEAL_DASH_GO_TO_CART_MODAL", 324, 1864);
        CLICK_CART_TIMER = new WishAnalyticsEvent("CLICK_CART_TIMER", 325, 1872);
        CLICK_CART_EDUCATION_MODAL_BUTTON = new WishAnalyticsEvent("CLICK_CART_EDUCATION_MODAL_BUTTON", 326, 1873);
        CLICK_WISHLOOK_BANNER = new WishAnalyticsEvent("CLICK_WISHLOOK_BANNER", 327, 1876);
        CLICK_MOBILE_NATIVE_BILLING_BOLETO_TAB = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_BOLETO_TAB", 328, 1961);
        CLICK_MOBILE_NATIVE_BILLING_NEXT_BOLETO = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_NEXT_BOLETO", 329, 1962);
        CLICK_MOBILE_NATIVE_BILLING_NEXT_BOLETO_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_NEXT_BOLETO_SUCCESS", 330, 1963);
        CLICK_MOBILE_NATIVE_BILLING_NEXT_BOLETO_FAILURE = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_NEXT_BOLETO_FAILURE", 331, 1964);
        CLICK_MOBILE_NATIVE_BOLETO_PLACE_ORDER = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BOLETO_PLACE_ORDER", 332, 1965);
        CLICK_MOBILE_NATIVE_BOLETO_PLACE_ORDER_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BOLETO_PLACE_ORDER_SUCCESS", 333, 1966);
        CLICK_MOBILE_NATIVE_BOLETO_PLACE_ORDER_FAILURE = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BOLETO_PLACE_ORDER_FAILURE", 334, 1967);
        CLICK_MOBILE_NATIVE_BILLING_FRIEND_FAMILY_TAB = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_FRIEND_FAMILY_TAB", 335, 1974);
        CLICK_MOBILE_NATIVE_FAMILY_PLACE_ORDER = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_FAMILY_PLACE_ORDER", 336, 1975);
        CLICK_MOBILE_NATIVE_FAMILY_PLACE_ORDER_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_FAMILY_PLACE_ORDER_SUCCESS", 337, 1976);
        CLICK_MOBILE_NATIVE_FAMILY_PLACE_ORDER_FAILURE = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_FAMILY_PLACE_ORDER_FAILURE", 338, 1977);
        CLICK_MOBILE_NATIVE_BILLING_NEXT_FAMILY = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_NEXT_FAMILY", 339, 1978);
        CLICK_MOBILE_NATIVE_BILLING_NEXT_FAMILY_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_NEXT_FAMILY_SUCCESS", 340, 1979);
        CLICK_MOBILE_NATIVE_BILLING_NEXT_FAMILY_FAILURE = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_NEXT_FAMILY_FAILURE", 341, 1980);
        CLICK_CROSS_PROMO_BANNER = new WishAnalyticsEvent("CLICK_CROSS_PROMO_BANNER", 342, 1984);
        CLICK_CROSS_PROMO_BUY_BLOCKER_ACTION = new WishAnalyticsEvent("CLICK_CROSS_PROMO_BUY_BLOCKER_ACTION", 343, 1985);
        CLICK_CROSS_PROMO_BUY_BLOCKER_CANCEL = new WishAnalyticsEvent("CLICK_CROSS_PROMO_BUY_BLOCKER_CANCEL", 344, 1986);
        CLICK_MOBILE_SIDE_NAV_OTHER_APPS = new WishAnalyticsEvent("CLICK_MOBILE_SIDE_NAV_OTHER_APPS", 345, 1991);
        CLICK_MOBILE_APP_LIST_ITEM = new WishAnalyticsEvent("CLICK_MOBILE_APP_LIST_ITEM", 346, 1992);
        CLICK_MOBILE_NATIVE_BILLING_BOKU_TAB = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_BOKU_TAB", 347, 1994);
        CLICK_MOBILE_NATIVE_BILLING_NEXT_BOKU = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BILLING_NEXT_BOKU", 348, 1995);
        CLICK_MOBILE_NATIVE_BOKU_INITIATE_ORDER = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BOKU_INITIATE_ORDER", 349, 1996);
        CLICK_MOBILE_NATIVE_BOKU_INITIATE_ORDER_SUCCESS = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BOKU_INITIATE_ORDER_SUCCESS", 350, 1997);
        CLICK_MOBILE_NATIVE_BOKU_INITIATE_ORDER_FAILURE = new WishAnalyticsEvent("CLICK_MOBILE_NATIVE_BOKU_INITIATE_ORDER_FAILURE", 351, 1998);
        $VALUES = (new WishAnalyticsEvent[] {
            IMPRESSION_MOBILE_SIGNUP_STEP_ONE, IMPRESSION_MOBILE_SIGNUP_STEP_TWO, IMPRESSION_MOBILE_SIGNUP_STEP_THREE, IMPRESSION_MOBILE_SIGNUP_NIAGARA_STEP_TWO, IMPRESSION_MOBILE_SIGNUP_NIAGARA_STEP_THREE, IMPRESSION_MOBILE_SIGNUP_NIAGARA_STEP_FOUR, IMPRESSION_MOBILE_CART, IMPRESSION_MOBILE_NATIVE_SHIPPING, IMPRESSION_MOBILE_NATIVE_BILLING, IMPRESSION_MOBILE_SELL_CAMERA, 
            IMPRESSION_MOBILE_SELL_IMAGE_CONFIRM, IMPRESSION_MOBILE_SELL_EDITOR, IMPRESSION_MOBILE_SELL_EDU, IMPRESSION_MOBILE_REQUEST_GIFT_CARD, IMPRESSION_MOBILE_REQUEST_GIFT_CARD_CONFIRM, IMPRESSION_MOBILE_SALE_PARTY, IMPRESSION_MOBILE_FACEBOOK_AUTOFILL_TOAST, IMPRESSION_MOBILE_FACEBOOK_AUTOFILLED_MSG, IMPRESSION_MOBILE_EMAIL_SIGN_UP, IMPRESSION_MOBILE_EMAIL_LOGIN, 
            IMPRESSION_MOBILE_EMAIL_FORGOT_PASSWORD, IMPRESSION_MOBILE_EMAIL_CHANGE_PASSWORD, IMPRESSION_MOBILE_EMAIL_UPDATE_PROFILE, IMPRESSION_MOBILE_FEED_ENDED_WIDGET, IMPRESSION_MOBILE_FEED_FILTER, IMPRESSION_MOBILE_REVIEW_CART, IMPRESSION_MOBILE_CHECKOUT_OFFER, IMPRESSION_MOBILE_CREDIT_COUNTER, IMPRESSION_MOBILE_CREDIT_BANNER, IMPRESSION_MOBILE_NATIVE_GIFT_DASHBOARD, 
            IMPRESSION_MOBILE_NATIVE_GIFT_FEED, IMPRESSION_MOBILE_NATIVE_GIFT_DETAILS, IMPRESSION_MOBILE_NATIVE_GIFT_CART, IMPRESSION_MOBILE_NATIVE_GIFT_EDIT_SHIPPING, IMPRESSION_MOBILE_NATIVE_GIFT_EDIT_BILLING, IMPRESSION_MOBILE_NATIVE_GIFT_COMPLETE, IMPRESSION_MOBILE_SIGNUP_GIFT_DASHBOARD, IMPRESSION_MOBILE_SIGNUP_GIFT_FEED, IMPRESSION_MOBILE_SIGNUP_GIFT_DETAILS, IMPRESSION_MOBILE_SIGNUP_GIFT_CART, 
            IMPRESSION_MOBILE_SIGNUP_GIFT_EDIT_SHIPPING, IMPRESSION_MOBILE_SIGNUP_GIFT_EDIT_BILLING, IMPRESSION_MOBILE_SIGNUP_GIFT_COMPLETE, IMPRESSION_MOBILE_LIVE_SUPPORT_CART, IMPRESSION_MOBILE_LIVE_SUPPORT_PROD_DETAILS, IMPRESSION_MOBILE_LIVE_SUPPORT_PENDING, IMPRESSION_MOBILE_ABANDONED_CART_NOTIFICATION, IMPRESSION_FIRST_LAUNCH, IMPRESSION_LOGIN_NOT_FROM_WISH_NOTIFICATION, IMPRESSION_MOBILE_NATIVE_MERCHANT_PAGE, 
            IMPRESSION_MOBILE_NATIVE_BILLING_ZIP_PAGE, IMPRESSION_MOBILE_NATIVE_PRODUCT_RATINGS, IMPRESSION_MOBILE_NATIVE_MERCHANT_RATINGS, IMPRESSION_SIGNUP_NOT_FROM_WISH_NOTIFICATION, IMPRESSION_MOBILE_RATE_TRANSACTION_PROMPT, IMPRESSION_MOBILE_SIGNUP_CATEGORY, IMPRESSION_MOBILE_ADDED_TO_CART_MODAL, IMPRESSION_MOBILE_INVITE_FRIENDS_BY_LINK, IMPRESSION_MOBILE_INVITE_FRIENDS_BY_LINK_PROMPT, IMPRESSION_MY_PROFILE, 
            IMPRESSION_OTHER_PROFILE, IMPRESSION_CROSS_PROMO_BANNER, IMPRESSION_CROSS_PROMO_BUY_BLOCKER, IMPRESSION_WISH_TO_CART_MODAL, IMPRESSION_MOBILE_UPSELL_MODAL, IMPRESSION_MOBILE_CART_ABANDON_OFFER, IMPRESSION_MOBILE_FREE_GIFTS_SCREEN, IMPRESSION_MOBILE_FREE_GIFT_ADD_TO_CART_MODAL, IMPRESSION_MOBILE_FREE_GIFT_SHIPPING_INFO, IMPRESSION_MOBILE_FREE_GIFT_SHIPPING_ERROR_MODAL, 
            IMPRESSION_MOBILE_FREE_GIFT_BILLING_INFO, IMPRESSION_MOBILE_FREE_GIFT_BILLING_ERROR_MODAL, IMPRESSION_MOBILE_FREE_GIFT_APPLIED_MODAL, IMPRESSION_MOBILE_SIGNUP_UPDATE_PROFILE, IMPRESSION_MOBILE_GOOGLE_APPINDEXING_WEB_GOOGLE, IMPRESSION_MOBILE_GOOGLE_APPINDEXING_WEB_OTHER, IMPRESSION_MOBILE_GOOGLE_APPINDEXING_APP_GOOGLE, IMPRESSION_MOBILE_GOOGLE_APPINDEXING_APP_OTHER, IMPRESSION_MOBILE_GOOGLE_APPINDEXING_CRAWLER, IMPRESSION_MOBILE_SIGNUP_INTROGRAPHIC_PAGE_ONE, 
            IMPRESSION_MOBILE_SIGNUP_INTROGRAPHIC_PAGE_TWO, IMPRESSION_MOBILE_SIGNUP_INTROGRAPHIC_PAGE_THREE, IMPRESSION_FREE_GIFTS_ABANDONMENT_MODAL, IMPRESSION_DEAL_DASH_START, IMPRESSION_DEAL_DASH_COUNTDOWN, IMPRESSION_DEAL_DASH_FEED, IMPRESSION_DEAL_DASH_WAIT, IMPRESSION_DEAL_DASH_MODAL, IMPRESSION_CART_EDUCATION_MODAL, CLICK_RELATED_PRODUCT, 
            CLICK_MOBILE_SEARCH, CLICK_MOBILE_SEARCH_HISTORY, CLICK_MOBILE_SEARCH_PRODUCT, CLICK_MOBILE_SEARCH_FRIEND, CLICK_MOBILE_HOME, CLICK_MOBILE_SIGNUP_STEP_THREE_NEXT, CLICK_MOBILE_SIDE_NAV_PROFILE, CLICK_MOBILE_SIDE_NAV_NOTIFICATIONS, CLICK_MOBILE_SIDE_NAV_WALLET, CLICK_MOBILE_SIDE_NAV_CART, 
            CLICK_MOBILE_SIDE_NAV_INVITE, CLICK_MOBILE_SIDE_NAV_ORDER_HISTORY, CLICK_MOBILE_SIDE_NAV_HELP, CLICK_MOBILE_SIDE_NAV_SETTINGS, CLICK_MOBILE_NATIVE_CHECKOUT, CLICK_MOBILE_NATIVE_PLACE_ORDER, CLICK_MOBILE_NATIVE_PLACE_ORDER_SUCCESS, CLICK_MOBILE_NATIVE_PLACE_ORDER_FAILURE, CLICK_MOBILE_NATIVE_PAYPAL_SUCCESS, CLICK_MOBILE_NATIVE_PAYPAL_FAILURE, 
            CLICK_MOBILE_NATIVE_SHIPPING_NEXT, CLICK_MOBILE_NATIVE_SHIPPING_NEXT_SUCCESS, CLICK_MOBILE_NATIVE_SHIPPING_NEXT_FAILURE, CLICK_MOBILE_NATIVE_BILLING_NEXT_PAYPAL, CLICK_MOBILE_NATIVE_BILLING_NEXT_CC, CLICK_MOBILE_NATIVE_BILLING_NEXT_CC_SUCCESS, CLICK_MOBILE_NATIVE_BILLING_NEXT_CC_FAILURE, CLICK_MOBILE_NATIVE_BILLING_SCAN, CLICK_MOBILE_NATIVE_BILLING_SCAN_SUCCESS, CLICK_MOBILE_NATIVE_EDIT_BILLING, 
            CLICK_MOBILE_NATIVE_EDIT_SHIPPING, CLICK_MOBILE_NATIVE_EDIT_BILLING_EMPTY, CLICK_MOBILE_NATIVE_EDIT_SHIPPING_EMPTY, CLICK_MOBILE_WALLET_ITEM, CLICK_MOBILE_NATIVE_AUTO_PLACE_ORDER, CLICK_MOBILE_NATIVE_AUTO_PLACE_ORDER_SUCCESS, CLICK_MOBILE_NATIVE_AUTO_PLACE_ORDER_FAILURE, CLICK_MOBILE_SIDE_NAV_SELL, CLICK_MOBILE_SELL_EDU_LEARN, CLICK_MOBILE_SELL_EDU_SKIP, 
            CLICK_MOBILE_SELL_EDU_CHANGE_PAGE, CLICK_MOBILE_SELL_EDU_GET_STARTED, CLICK_MOBILE_SELL_CAMERA_TAKE_PIC, CLICK_MOBILE_SELL_CAMERA_GALLERY, CLICK_MOBILE_SELL_IMAGE_CONFIRM, CLICK_MOBILE_SELL_IMAGE_CANCEL, CLICK_MOBILE_SELL_ADD_EXTRA_PHOTO, CLICK_MOBILE_SELL_CANCEL, CLICK_MOBILE_SELL_SUBMIT, CLICK_MOBILE_REQUEST_GIFT_CARD, 
            CLICK_MOBILE_REQUEST_GIFT_CARD_CONFIRM, CLICK_MOBILE_SALE_PARTY_SELL, CLICK_MOBILE_SALE_PARTY_SHOP, CLICK_MOBILE_SIDE_NAV_SALE_PARTY, CLICK_GIFT_GIFT_IT_BUTTON, CLICK_MOBILE_SIDE_NAV_UPCOMMING_BIRTHDAY, CLICK_MOBILE_SHIPPING_AUTOFILL_TOAST, CLICK_MOBILE_SHIPPING_AUTOFILL_TOAST_MIN, CLICK_MOBILE_SHIPPING_AUTOFILL_TOAST_SUC, CLICK_MOBILE_BILLING_AUTOFILL_TOAST, 
            CLICK_MOBILE_BILLING_AUTOFILL_TOAST_MIN, CLICK_MOBILE_BILLING_AUTOFILL_TOAST_SUC, CLICK_MOBILE_BILLING_AUTOFILL_DISMISS, CLICK_MOBILE_NATIVE_BILLING_NEXT_FACEBOOK, CLICK_MOBILE_NATIVE_PAYPAL_ORDER, CLICK_MOBILE_NATIVE_FACEBOOK_ORDER, CLICK_MOBILE_NATIVE_FACEBOOK_ORDER_SUCCESS, CLICK_MOBILE_NATIVE_FACEBOOK_ORDER_FAILURE, CLICK_MOBILE_SPLASH_EMAIL_SIGN_UP, CLICK_MOBILE_SPLASH_EMAIL_LOGIN, 
            CLICK_MOBILE_EMAIL_SIGN_UP, CLICK_MOBILE_EMAIL_FORGOT_PASSWORD, CLICK_MOBILE_EMAIL_LOGIN, CLICK_MOBILE_EMAIL_UPDATE_PROFILE_NEXT, CLICK_MOBILE_EMAIL_UPDATE_PROFILE_SKIP, CLICK_MOBILE_EMAIL_CHANGE_PASSWORD, CLICK_MOBILE_NATIVE_PAYPAL_AUTO_ORDER, CLICK_MOBILE_NATIVE_FACEBOOK_AUTO_ORDER, CLICK_MOBILE_FEED_ENDED_WIDGET, CLICK_MOBILE_SPLASH_FACEBOOK_LOGIN, 
            CLICK_MOBILE_SORT_MODE, CLICK_MOBILE_DEEP_LINK_SORT_MODE, CLICK_MOBILE_SIDE_NAV_SEARCH, CLICK_MOBILE_SEARCH_POPULAR, CLICK_MOBILE_NATIVE_GWALLET_CHANGE_SHIPPING, CLICK_MOBILE_NATIVE_BUY_WITH_GOOGLE, CLICK_MOBILE_NATIVE_GWALLET_FETCH, CLICK_MOBILE_NATIVE_GWALLET_FETCH_SUCCESS, CLICK_MOBILE_NATIVE_GWALLET_FETCH_FAILURE, CLICK_MOBILE_NATIVE_BILLING_NEXT_GWALLET, 
            CLICK_MOBILE_NATIVE_GWALLET_FULL_FETCH, CLICK_MOBILE_NATIVE_GWALLET_FULL_SUCCESS, CLICK_MOBILE_NATIVE_GWALLET_FULL_FAILURE, CLICK_MOBILE_NATIVE_GWALLET_ORDER, CLICK_MOBILE_NATIVE_GWALLET_ORDER_SUCCESS, CLICK_MOBILE_NATIVE_GWALLET_ORDER_FAILURE, CLICK_MOBILE_CHOME_CATEGORY, CLICK_MOBILE_CHOME_COLLECTION, CLICK_MOBILE_SIGNUP_GIFTING_SKIP, CLICK_MOBILE_GIFTING_DASH_SLIDER_FEED, 
            CLICK_MOBILE_GIFTING_DASH_FRIEND_FEED, CLICK_MOBILE_GIFTING_DASH_FB_LOGIN, CLICK_MOBILE_GIFTING_DASH_COLLECTION, CLICK_MOBILE_GIFTING_BUY_MORE_GIFTS, CLICK_MOBILE_GIFTING_DONE_BUYING_GIFTS, CLICK_MOBILE_GIFTING_EDIT_SHIPPING, CLICK_MOBILE_GIFTING_EDIT_BILLING, CLICK_MOBILE_GIFTING_PLACE_ORDER, CLICK_MOBILE_GIFTING_PLACE_ORDER_SUCCESS, CLICK_MOBILE_GIFTING_PLACE_ORDER_FAILURE, 
            CLICK_MOBILE_GIFTING_DASH_FRIEND_FACE, CLICK_MOBILE_GIFTING_NATIVE_CHECKOUT, CLICK_MOBILE_LIVE_SUPPORT_CART, CLICK_MOBILE_LIVE_SUPPORT_PROD_DETAILS, CLICK_MOBILE_LIVE_SUPPORT_PENDING, CLICK_MOBILE_ABANDONED_CART_NOTIFICATION, CLICK_MOBILE_NATIVE_PAYPAL_CANCEL, CLICK_MOBILE_NATIVE_PAYPAL_PAY_SUCCESS, CLICK_MOBILE_NATIVE_PAYPAL_PAY_ERROR, CLICK_MOBILE_NATIVE_PAYPAL_PREPAY_SUCCESS, 
            CLICK_MOBILE_NATIVE_PAYPAL_PREPAY_ERROR, CLICK_MOBILE_NATIVE_PAYPAL_VERIFY_ERROR, CLICK_MOBILE_NATIVE_PAYPAL_VERIFY_SUCCESS, CLICK_MOBILE_EXTRA_PHOTOS, CLICK_MOBILE_FEED_EXTRA_PHOTOS, CLICK_MOBILE_NATIVE_MERCHANT_CHANGE_TAB, CLICK_MOBILE_NATIVE_MERCHANT_VIEW_RATING, CLICK_MOBILE_NATIVE_BILLING_ZIP_NEXT, CLICK_MOBILE_DETAILS_MERCHANT_STORE, CLICK_MOBILE_DETAILS_MERCHANT_RATING, 
            CLICK_MOBILE_DETAILS_PRODUCT_RATING, CLICK_MOBILE_DETAILS_CHANGE_RELATED_TAB, CLICK_MOBILE_RATINGS_VIEW_PRODUCT, CLICK_MOBILE_RATINGS_VISIT_STORE, CLICK_MOBILE_SIGNUP_CATEGORY_NEXT, CLICK_MOBILE_ADDED_TO_CART_MODAL_SHOP, CLICK_MOBILE_ADDED_TO_CART_MODAL_VIEW_CART, CLICK_MOBILE_NATIVE_BILLING_CC_TAB, CLICK_MOBILE_NATIVE_BILLING_GWALLET_TAB, CLICK_MOBILE_NATIVE_BILLING_PAYPAL_TAB, 
            CLICK_MOBILE_NATIVE_COLLECTION, CLICK_MOBILE_NATIVE_CATEGORY, CLICK_MOBILE_NATIVE_FOOTER_COLLECTION, CLICK_MOBILE_NATIVE_CATEGORY_START_SCROLL, CLICK_MOBILE_NATIVE_CATEGORY_END_SCROLL, CLICK_MOBILE_NATIVE_COLLECTION_START_SCROLL, CLICK_MOBILE_NATIVE_COLLECTION_END_SCROLL, CLICK_MOBILE_NATIVE_SIZING_CHART, CLICK_MOBILE_NATIVE_FOOTER_COLLECTION_START_SCROLL, CLICK_MOBILE_NATIVE_FOOTER_COLLECTION_END_SCROLL, 
            CLICK_MOBILE_INVITE_BY_LINK_EMAIL, CLICK_MOBILE_INVITE_BY_LINK_SMS, CLICK_MOBILE_INVITE_BY_LINK_SHARE, CLICK_MOBILE_INVITE_BY_LINK_DONE, CLICK_MOBILE_INVITE_BY_LINK_PROMPT_EMAIL, CLICK_MOBILE_INVITE_BY_LINK_PROMPT_SMS, CLICK_MOBILE_INVITE_BY_LINK_PROMPT_SHARE, CLICK_MOBILE_INVITE_BY_LINK_PROMPT_DONE, CLICK_MOBILE_DETAILS_VIEW_DESCRIPTION, CLICK_MOBILE_ZOOM_PRODUCT_PHOTO, 
            CLICK_RATING_PHOTO, CLICK_SCROLL_MAIN_PRODUCT_IMAGE, CLICK_MOBILE_DETAILS_GET_CREDIT, CLICK_MOBILE_CART_GET_CREDIT, CLICK_MOBILE_DETAILS_SEARCH, CLICK_MOBILE_NATIVE_BILLING_VISA_TAB, CLICK_MOBILE_NATIVE_BILLING_SAVE_VISA, CLICK_MOBILE_NATIVE_BILLING_SAVE_VISA_SUCCESS, CLICK_MOBILE_NATIVE_BILLING_SAVE_VISA_FAILURE, CLICK_MOBILE_NATIVE_BILLING_VISA_FETCHED, 
            CLICK_MOBILE_NATIVE_BILLING_VISA_CANCEL, CLICK_MOBILE_NATIVE_BILLING_VISA_ERROR, CLICK_MOBILE_NATIVE_BILLING_VISA_START, CLICK_MOBILE_RECOMMEND, CLICK_MOBILE_ADD_TO_CART_CANCEL, CLICK_MOBILE_ADD_TO_CART_BUY, CLICK_MOBILE_CART_ITEM_CHANGE, CLICK_MOBILE_FEED_FILTER_REMOVE, CLICK_MOBILE_FEED_FILTER_NAV, CLICK_MOBILE_FEED_FILTER_SELECT, 
            CLICK_MOBILE_FEED_FILTER_APPLY, CLICK_MOBILE_FEED_FILTER_CANCEL, CLICK_MOBILE_FEED_FILTER_SEARCH, CLICK_MOBILE_PRODUCT_DETAIL_SECTION, CLICK_MOBILE_NATIVE_PAYPAL_FUTURE_PAY_ERROR, CLICK_MOBILE_NATIVE_PAYPAL_FUTURE_PAY_SUCCESS, CLICK_MOBILE_NATIVE_PAYPAL_AUTH_ERROR, CLICK_MOBILE_NATIVE_PAYPAL_AUTH_SUCCESS, CLICK_WISH_TO_CART_MODAL_BUY, CLICK_WISH_TO_CART_MODAL_CANCEL, 
            CLICK_MOBILE_SIGNUP_EMAIL_SUGGEST, CLICK_MOBILE_SIGNUP_EMAIL_CONFIRM_FAIL, CLICK_MOBILE_SIGNUP_VIEW_WITH_NONE, CLICK_MOBILE_SIGNUP_VIEW_WITH_CONFIRM, CLICK_MOBILE_SIGNUP_VIEW_WITH_SUGGEST, CLICK_MOBILE_SIGNUP_VIEW_WITH_BOTH, CLICK_MOBILE_SIGNUP_SUCCESS_WITH_NONE, CLICK_MOBILE_SIGNUP_SUCCESS_WITH_CONFIRM, CLICK_MOBILE_SIGNUP_SUCCESS_WITH_SUGGEST, CLICK_MOBILE_SIGNUP_SUCCESS_WITH_BOTH, 
            CLICK_MOBILE_CART_CONTINUE_SHOPPING, CLICK_MOBILE_UPSELL_MODAL_BUY_BUTTON, CLICK_MOBILE_UPSELL_MODAL_PRODUCT_SCROLL, CLICK_MOBILE_UPSELL_MODAL_NO_THANKS_BUTTON, CLICK_MOBILE_FREE_GIFT_CLAIM_BUTTON, CLICK_MOBILE_FREE_GIFT_CLAIM_CANCEL_BUTTON, CLICK_MOBILE_FREE_GIFT_SCROLL_PRODUCT, CLICK_MOBILE_FREE_GIFT_SHIPPING_SAME_AS_CHECKBOX, CLICK_MOBILE_FREE_GIFT_SHIPPING_NEXT_BUTTON, CLICK_MOBILE_FREE_GIFT_SHIPPING_CANCEL_BUTTON, 
            CLICK_MOBILE_FREE_GIFT_BILLING_REDEEM_BUTTON, CLICK_MOBILE_FREE_GIFT_BILLING_CANCEL_BUTTON, CLICK_MOBILE_FREE_GIFT_APPLIED_MODAL_CONTINUE, CLICK_MOBILE_FREE_GIFT_SHIPPING_BACK_BUTTON, CLICK_MOBILE_FREE_GIFT_BILLING_BACK_BUTTON, CLICK_MOBILE_FREE_GIFT_ADD_TO_CART_MODAL_CANCEL, CLICK_MOBILE_FREE_GIFT_ADD_TO_CART_MODAL_BUY, CLICK_MOBILE_SIGNUP_UPDATE_PROFILE_NEXT, CLICK_MOBILE_SIGNUP_UPDATE_PROFILE_SKIP, CLICK_MOBILE_NATIVE_BILLING_OXXO_TAB, 
            CLICK_MOBILE_NATIVE_BILLING_NEXT_OXXO, CLICK_MOBILE_NATIVE_BILLING_NEXT_OXXO_SUCCESS, CLICK_MOBILE_NATIVE_BILLING_NEXT_OXXO_FAILURE, CLICK_MOBILE_NATIVE_OXXO_PLACE_ORDER, CLICK_MOBILE_NATIVE_OXXO_PLACE_ORDER_SUCCESS, CLICK_MOBILE_NATIVE_OXXO_PLACE_ORDER_FAILURE, CLICK_MOBILE_SIDE_FAQ, CLICK_MOBILE_SIGNUP_INTROGRAPHIC_NEXT, CLICK_MOBILE_SIGNUP_INTROGRAPHIC_SKIP, CLICK_MOBILE_FREE_GIFT_ABANDONMENT_MODAL_PROCEED, 
            CLICK_MOBILE_FREE_GIFT_ABANDONMENT_MODAL_RETURN, CLICK_DEAL_DASH_TAB, CLICK_DEAL_DASH_START, CLICK_DEAL_DASH_LEAVE, CLICK_DEAL_DASH_GO_TO_CART_MODAL, CLICK_CART_TIMER, CLICK_CART_EDUCATION_MODAL_BUTTON, CLICK_WISHLOOK_BANNER, CLICK_MOBILE_NATIVE_BILLING_BOLETO_TAB, CLICK_MOBILE_NATIVE_BILLING_NEXT_BOLETO, 
            CLICK_MOBILE_NATIVE_BILLING_NEXT_BOLETO_SUCCESS, CLICK_MOBILE_NATIVE_BILLING_NEXT_BOLETO_FAILURE, CLICK_MOBILE_NATIVE_BOLETO_PLACE_ORDER, CLICK_MOBILE_NATIVE_BOLETO_PLACE_ORDER_SUCCESS, CLICK_MOBILE_NATIVE_BOLETO_PLACE_ORDER_FAILURE, CLICK_MOBILE_NATIVE_BILLING_FRIEND_FAMILY_TAB, CLICK_MOBILE_NATIVE_FAMILY_PLACE_ORDER, CLICK_MOBILE_NATIVE_FAMILY_PLACE_ORDER_SUCCESS, CLICK_MOBILE_NATIVE_FAMILY_PLACE_ORDER_FAILURE, CLICK_MOBILE_NATIVE_BILLING_NEXT_FAMILY, 
            CLICK_MOBILE_NATIVE_BILLING_NEXT_FAMILY_SUCCESS, CLICK_MOBILE_NATIVE_BILLING_NEXT_FAMILY_FAILURE, CLICK_CROSS_PROMO_BANNER, CLICK_CROSS_PROMO_BUY_BLOCKER_ACTION, CLICK_CROSS_PROMO_BUY_BLOCKER_CANCEL, CLICK_MOBILE_SIDE_NAV_OTHER_APPS, CLICK_MOBILE_APP_LIST_ITEM, CLICK_MOBILE_NATIVE_BILLING_BOKU_TAB, CLICK_MOBILE_NATIVE_BILLING_NEXT_BOKU, CLICK_MOBILE_NATIVE_BOKU_INITIATE_ORDER, 
            CLICK_MOBILE_NATIVE_BOKU_INITIATE_ORDER_SUCCESS, CLICK_MOBILE_NATIVE_BOKU_INITIATE_ORDER_FAILURE
        });
    }
}
