sh script.sh 10-WRITE_SETTING.txt uber/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt alibaba/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt 360-security/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt facebook-messenger/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt facebook-app/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt whatsapp/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt QR-barcode-source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt accuweather-source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt emoji-source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt google-photos/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt history-source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt kik-source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt king_J_bible_source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt kodi-source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt kohl-source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt lyft-source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt music-player-pro-source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt music-player_source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt nbc_source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt photo-grid-source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt pinterest_source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt skype-source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt snap_chat_source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt sound-cloud_source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt tinder-source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt transit_source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt translator-google_source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt voice-app_source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt wallmart-source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt weather-widget-source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt weatherchannel-source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt wellfargo/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt wish-source/ 10-res-WRITE_SETTING.txt
sh script.sh 10-WRITE_SETTING.txt youtube-source/ 10-res-WRITE_SETTING.txt
