sh script.sh 8-WRITE_CONTACT.txt uber/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt alibaba/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt 360-security/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt facebook-messenger/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt facebook-app/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt whatsapp/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt QR-barcode-source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt accuweather-source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt emoji-source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt google-photos/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt history-source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt kik-source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt king_J_bible_source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt kodi-source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt kohl-source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt lyft-source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt music-player-pro-source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt music-player_source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt nbc_source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt photo-grid-source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt pinterest_source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt skype-source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt snap_chat_source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt sound-cloud_source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt tinder-source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt transit_source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt translator-google_source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt voice-app_source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt wallmart-source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt weather-widget-source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt weatherchannel-source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt wellfargo/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt wish-source/ 8-res-WRITE_CONTACT.txt
sh script.sh 8-WRITE_CONTACT.txt youtube-source/ 8-res-WRITE_CONTACT.txt
