// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.google.android.libraries.phonenumbers;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public final class CountryCodeToRegionCodeMap
{

    static Map getCountryCodeToRegionCodeMap()
    {
        HashMap hashmap = new HashMap(286);
        ArrayList arraylist = new ArrayList(25);
        arraylist.add("US");
        arraylist.add("AG");
        arraylist.add("AI");
        arraylist.add("AS");
        arraylist.add("BB");
        arraylist.add("BM");
        arraylist.add("BS");
        arraylist.add("CA");
        arraylist.add("DM");
        arraylist.add("DO");
        arraylist.add("GD");
        arraylist.add("GU");
        arraylist.add("JM");
        arraylist.add("KN");
        arraylist.add("KY");
        arraylist.add("LC");
        arraylist.add("MP");
        arraylist.add("MS");
        arraylist.add("PR");
        arraylist.add("SX");
        arraylist.add("TC");
        arraylist.add("TT");
        arraylist.add("VC");
        arraylist.add("VG");
        arraylist.add("VI");
        hashmap.put(Integer.valueOf(1), arraylist);
        arraylist = new ArrayList(2);
        arraylist.add("RU");
        arraylist.add("KZ");
        hashmap.put(Integer.valueOf(7), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("EG");
        hashmap.put(Integer.valueOf(20), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("ZA");
        hashmap.put(Integer.valueOf(27), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GR");
        hashmap.put(Integer.valueOf(30), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("NL");
        hashmap.put(Integer.valueOf(31), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BE");
        hashmap.put(Integer.valueOf(32), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("FR");
        hashmap.put(Integer.valueOf(33), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("ES");
        hashmap.put(Integer.valueOf(34), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("HU");
        hashmap.put(Integer.valueOf(36), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("IT");
        hashmap.put(Integer.valueOf(39), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("RO");
        hashmap.put(Integer.valueOf(40), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CH");
        hashmap.put(Integer.valueOf(41), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("AT");
        hashmap.put(Integer.valueOf(43), arraylist);
        arraylist = new ArrayList(4);
        arraylist.add("GB");
        arraylist.add("GG");
        arraylist.add("IM");
        arraylist.add("JE");
        hashmap.put(Integer.valueOf(44), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("DK");
        hashmap.put(Integer.valueOf(45), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SE");
        hashmap.put(Integer.valueOf(46), arraylist);
        arraylist = new ArrayList(2);
        arraylist.add("NO");
        arraylist.add("SJ");
        hashmap.put(Integer.valueOf(47), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PL");
        hashmap.put(Integer.valueOf(48), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("DE");
        hashmap.put(Integer.valueOf(49), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PE");
        hashmap.put(Integer.valueOf(51), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MX");
        hashmap.put(Integer.valueOf(52), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CU");
        hashmap.put(Integer.valueOf(53), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("AR");
        hashmap.put(Integer.valueOf(54), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BR");
        hashmap.put(Integer.valueOf(55), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CL");
        hashmap.put(Integer.valueOf(56), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CO");
        hashmap.put(Integer.valueOf(57), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("VE");
        hashmap.put(Integer.valueOf(58), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MY");
        hashmap.put(Integer.valueOf(60), arraylist);
        arraylist = new ArrayList(3);
        arraylist.add("AU");
        arraylist.add("CC");
        arraylist.add("CX");
        hashmap.put(Integer.valueOf(61), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("ID");
        hashmap.put(Integer.valueOf(62), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PH");
        hashmap.put(Integer.valueOf(63), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("NZ");
        hashmap.put(Integer.valueOf(64), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SG");
        hashmap.put(Integer.valueOf(65), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TH");
        hashmap.put(Integer.valueOf(66), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("JP");
        hashmap.put(Integer.valueOf(81), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("KR");
        hashmap.put(Integer.valueOf(82), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("VN");
        hashmap.put(Integer.valueOf(84), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CN");
        hashmap.put(Integer.valueOf(86), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TR");
        hashmap.put(Integer.valueOf(90), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("IN");
        hashmap.put(Integer.valueOf(91), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PK");
        hashmap.put(Integer.valueOf(92), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("AF");
        hashmap.put(Integer.valueOf(93), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("LK");
        hashmap.put(Integer.valueOf(94), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MM");
        hashmap.put(Integer.valueOf(95), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("IR");
        hashmap.put(Integer.valueOf(98), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SS");
        hashmap.put(Integer.valueOf(211), arraylist);
        arraylist = new ArrayList(2);
        arraylist.add("MA");
        arraylist.add("EH");
        hashmap.put(Integer.valueOf(212), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("DZ");
        hashmap.put(Integer.valueOf(213), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TN");
        hashmap.put(Integer.valueOf(216), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("LY");
        hashmap.put(Integer.valueOf(218), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GM");
        hashmap.put(Integer.valueOf(220), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SN");
        hashmap.put(Integer.valueOf(221), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MR");
        hashmap.put(Integer.valueOf(222), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("ML");
        hashmap.put(Integer.valueOf(223), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GN");
        hashmap.put(Integer.valueOf(224), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CI");
        hashmap.put(Integer.valueOf(225), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BF");
        hashmap.put(Integer.valueOf(226), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("NE");
        hashmap.put(Integer.valueOf(227), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TG");
        hashmap.put(Integer.valueOf(228), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BJ");
        hashmap.put(Integer.valueOf(229), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MU");
        hashmap.put(Integer.valueOf(230), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("LR");
        hashmap.put(Integer.valueOf(231), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SL");
        hashmap.put(Integer.valueOf(232), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GH");
        hashmap.put(Integer.valueOf(233), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("NG");
        hashmap.put(Integer.valueOf(234), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TD");
        hashmap.put(Integer.valueOf(235), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CF");
        hashmap.put(Integer.valueOf(236), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CM");
        hashmap.put(Integer.valueOf(237), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CV");
        hashmap.put(Integer.valueOf(238), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("ST");
        hashmap.put(Integer.valueOf(239), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GQ");
        hashmap.put(Integer.valueOf(240), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GA");
        hashmap.put(Integer.valueOf(241), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CG");
        hashmap.put(Integer.valueOf(242), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CD");
        hashmap.put(Integer.valueOf(243), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("AO");
        hashmap.put(Integer.valueOf(244), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GW");
        hashmap.put(Integer.valueOf(245), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("IO");
        hashmap.put(Integer.valueOf(246), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("AC");
        hashmap.put(Integer.valueOf(247), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SC");
        hashmap.put(Integer.valueOf(248), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SD");
        hashmap.put(Integer.valueOf(249), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("RW");
        hashmap.put(Integer.valueOf(250), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("ET");
        hashmap.put(Integer.valueOf(251), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SO");
        hashmap.put(Integer.valueOf(252), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("DJ");
        hashmap.put(Integer.valueOf(253), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("KE");
        hashmap.put(Integer.valueOf(254), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TZ");
        hashmap.put(Integer.valueOf(255), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("UG");
        hashmap.put(Integer.valueOf(256), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BI");
        hashmap.put(Integer.valueOf(257), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MZ");
        hashmap.put(Integer.valueOf(258), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("ZM");
        hashmap.put(Integer.valueOf(260), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MG");
        hashmap.put(Integer.valueOf(261), arraylist);
        arraylist = new ArrayList(2);
        arraylist.add("RE");
        arraylist.add("YT");
        hashmap.put(Integer.valueOf(262), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("ZW");
        hashmap.put(Integer.valueOf(263), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("NA");
        hashmap.put(Integer.valueOf(264), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MW");
        hashmap.put(Integer.valueOf(265), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("LS");
        hashmap.put(Integer.valueOf(266), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BW");
        hashmap.put(Integer.valueOf(267), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SZ");
        hashmap.put(Integer.valueOf(268), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("KM");
        hashmap.put(Integer.valueOf(269), arraylist);
        arraylist = new ArrayList(2);
        arraylist.add("SH");
        arraylist.add("TA");
        hashmap.put(Integer.valueOf(290), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("ER");
        hashmap.put(Integer.valueOf(291), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("AW");
        hashmap.put(Integer.valueOf(297), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("FO");
        hashmap.put(Integer.valueOf(298), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GL");
        hashmap.put(Integer.valueOf(299), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GI");
        hashmap.put(Integer.valueOf(350), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PT");
        hashmap.put(Integer.valueOf(351), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("LU");
        hashmap.put(Integer.valueOf(352), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("IE");
        hashmap.put(Integer.valueOf(353), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("IS");
        hashmap.put(Integer.valueOf(354), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("AL");
        hashmap.put(Integer.valueOf(355), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MT");
        hashmap.put(Integer.valueOf(356), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CY");
        hashmap.put(Integer.valueOf(357), arraylist);
        arraylist = new ArrayList(2);
        arraylist.add("FI");
        arraylist.add("AX");
        hashmap.put(Integer.valueOf(358), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BG");
        hashmap.put(Integer.valueOf(359), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("LT");
        hashmap.put(Integer.valueOf(370), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("LV");
        hashmap.put(Integer.valueOf(371), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("EE");
        hashmap.put(Integer.valueOf(372), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MD");
        hashmap.put(Integer.valueOf(373), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("AM");
        hashmap.put(Integer.valueOf(374), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BY");
        hashmap.put(Integer.valueOf(375), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("AD");
        hashmap.put(Integer.valueOf(376), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MC");
        hashmap.put(Integer.valueOf(377), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SM");
        hashmap.put(Integer.valueOf(378), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("VA");
        hashmap.put(Integer.valueOf(379), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("UA");
        hashmap.put(Integer.valueOf(380), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("RS");
        hashmap.put(Integer.valueOf(381), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("ME");
        hashmap.put(Integer.valueOf(382), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("HR");
        hashmap.put(Integer.valueOf(385), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SI");
        hashmap.put(Integer.valueOf(386), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BA");
        hashmap.put(Integer.valueOf(387), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MK");
        hashmap.put(Integer.valueOf(389), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CZ");
        hashmap.put(Integer.valueOf(420), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SK");
        hashmap.put(Integer.valueOf(421), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("LI");
        hashmap.put(Integer.valueOf(423), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("FK");
        hashmap.put(Integer.valueOf(500), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BZ");
        hashmap.put(Integer.valueOf(501), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GT");
        hashmap.put(Integer.valueOf(502), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SV");
        hashmap.put(Integer.valueOf(503), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("HN");
        hashmap.put(Integer.valueOf(504), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("NI");
        hashmap.put(Integer.valueOf(505), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CR");
        hashmap.put(Integer.valueOf(506), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PA");
        hashmap.put(Integer.valueOf(507), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PM");
        hashmap.put(Integer.valueOf(508), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("HT");
        hashmap.put(Integer.valueOf(509), arraylist);
        arraylist = new ArrayList(3);
        arraylist.add("GP");
        arraylist.add("BL");
        arraylist.add("MF");
        hashmap.put(Integer.valueOf(590), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BO");
        hashmap.put(Integer.valueOf(591), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GY");
        hashmap.put(Integer.valueOf(592), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("EC");
        hashmap.put(Integer.valueOf(593), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GF");
        hashmap.put(Integer.valueOf(594), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PY");
        hashmap.put(Integer.valueOf(595), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MQ");
        hashmap.put(Integer.valueOf(596), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SR");
        hashmap.put(Integer.valueOf(597), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("UY");
        hashmap.put(Integer.valueOf(598), arraylist);
        arraylist = new ArrayList(2);
        arraylist.add("CW");
        arraylist.add("BQ");
        hashmap.put(Integer.valueOf(599), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TL");
        hashmap.put(Integer.valueOf(670), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("NF");
        hashmap.put(Integer.valueOf(672), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BN");
        hashmap.put(Integer.valueOf(673), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("NR");
        hashmap.put(Integer.valueOf(674), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PG");
        hashmap.put(Integer.valueOf(675), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TO");
        hashmap.put(Integer.valueOf(676), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SB");
        hashmap.put(Integer.valueOf(677), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("VU");
        hashmap.put(Integer.valueOf(678), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("FJ");
        hashmap.put(Integer.valueOf(679), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PW");
        hashmap.put(Integer.valueOf(680), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("WF");
        hashmap.put(Integer.valueOf(681), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("CK");
        hashmap.put(Integer.valueOf(682), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("NU");
        hashmap.put(Integer.valueOf(683), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("WS");
        hashmap.put(Integer.valueOf(685), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("KI");
        hashmap.put(Integer.valueOf(686), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("NC");
        hashmap.put(Integer.valueOf(687), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TV");
        hashmap.put(Integer.valueOf(688), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PF");
        hashmap.put(Integer.valueOf(689), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TK");
        hashmap.put(Integer.valueOf(690), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("FM");
        hashmap.put(Integer.valueOf(691), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MH");
        hashmap.put(Integer.valueOf(692), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("001");
        hashmap.put(Integer.valueOf(800), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("001");
        hashmap.put(Integer.valueOf(808), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("KP");
        hashmap.put(Integer.valueOf(850), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("HK");
        hashmap.put(Integer.valueOf(852), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MO");
        hashmap.put(Integer.valueOf(853), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("KH");
        hashmap.put(Integer.valueOf(855), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("LA");
        hashmap.put(Integer.valueOf(856), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("001");
        hashmap.put(Integer.valueOf(870), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("001");
        hashmap.put(Integer.valueOf(878), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BD");
        hashmap.put(Integer.valueOf(880), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("001");
        hashmap.put(Integer.valueOf(881), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("001");
        hashmap.put(Integer.valueOf(882), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("001");
        hashmap.put(Integer.valueOf(883), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TW");
        hashmap.put(Integer.valueOf(886), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("001");
        hashmap.put(Integer.valueOf(888), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MV");
        hashmap.put(Integer.valueOf(960), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("LB");
        hashmap.put(Integer.valueOf(961), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("JO");
        hashmap.put(Integer.valueOf(962), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SY");
        hashmap.put(Integer.valueOf(963), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("IQ");
        hashmap.put(Integer.valueOf(964), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("KW");
        hashmap.put(Integer.valueOf(965), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("SA");
        hashmap.put(Integer.valueOf(966), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("YE");
        hashmap.put(Integer.valueOf(967), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("OM");
        hashmap.put(Integer.valueOf(968), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("PS");
        hashmap.put(Integer.valueOf(970), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("AE");
        hashmap.put(Integer.valueOf(971), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("IL");
        hashmap.put(Integer.valueOf(972), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BH");
        hashmap.put(Integer.valueOf(973), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("QA");
        hashmap.put(Integer.valueOf(974), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("BT");
        hashmap.put(Integer.valueOf(975), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("MN");
        hashmap.put(Integer.valueOf(976), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("NP");
        hashmap.put(Integer.valueOf(977), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("001");
        hashmap.put(Integer.valueOf(979), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TJ");
        hashmap.put(Integer.valueOf(992), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("TM");
        hashmap.put(Integer.valueOf(993), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("AZ");
        hashmap.put(Integer.valueOf(994), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("GE");
        hashmap.put(Integer.valueOf(995), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("KG");
        hashmap.put(Integer.valueOf(996), arraylist);
        arraylist = new ArrayList(1);
        arraylist.add("UZ");
        hashmap.put(Integer.valueOf(998), arraylist);
        return hashmap;
    }
}
