// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.weather.commons.analytics;


// Referenced classes of package com.weather.commons.analytics:
//            LocalyticsBuckets

public static final class maxTime extends Enum
    implements maxTime
{

    private static final TEN_SECONDS_AND_ABOVE $VALUES[];
    public static final TEN_SECONDS_AND_ABOVE EIGHTEEN_HUNDRED_TO_TWO_THOUSAND_MILLI_SECONDS;
    public static final TEN_SECONDS_AND_ABOVE EIGHT_HUNDRED_TO_THOUSAND_MILLI_SECONDS;
    public static final TEN_SECONDS_AND_ABOVE FIFTY_TO_ONE_HUNDRED_MILLI_SECOND;
    public static final TEN_SECONDS_AND_ABOVE FOURTEEN_TO_SIXTEEN_HUNDRED_MILLI_SECONDS;
    public static final TEN_SECONDS_AND_ABOVE FOUR_SECONDS_TO_TEN_SECONDS;
    public static final TEN_SECONDS_AND_ABOVE FOUR_TO_SIX_HUNDRED_MILLI_SECONDS;
    public static final TEN_SECONDS_AND_ABOVE ONE_THOUSAND_TO_TWELEVE_HUNDRED_MILLI_SECONDS;
    public static final TEN_SECONDS_AND_ABOVE ONE_TO_TWO_HUNDRED_MILLI_SECOND;
    public static final TEN_SECONDS_AND_ABOVE SIXTEEN_TO_EIGHTEEN_HUNDRED_MILLI_SECONDS;
    public static final TEN_SECONDS_AND_ABOVE SIX_TO_EIGHT_HUNDRED_MILLI_SECONDS;
    public static final TEN_SECONDS_AND_ABOVE TEN_SECONDS_AND_ABOVE;
    public static final TEN_SECONDS_AND_ABOVE THIRTY_EIGHT_HUNDRED_MILLI_SECONDS_TO_FOUR_SECONDS;
    public static final TEN_SECONDS_AND_ABOVE THIRTY_FOUR_TO_THIRTY_SIX_HUNDRED_MILLI_SECONDS;
    public static final TEN_SECONDS_AND_ABOVE THIRTY_SIX_TO_THIRTY_EIGHT_HUNDRED_MILLI_SECONDS;
    public static final TEN_SECONDS_AND_ABOVE THIRTY_TWO_TO_THIRTY_FOUR_HUNDRED_MILLI_SECONDS;
    public static final TEN_SECONDS_AND_ABOVE THREE_THOUSAND_TO_THIRTY_TWO_HUNDRED_MILLI_SECONDS;
    public static final TEN_SECONDS_AND_ABOVE TWELVE_HUNDRED_TO_FOURTEEN_HUNDRED_MILLI_SECONDS;
    public static final TEN_SECONDS_AND_ABOVE TWENTY_EIGHT_HUNDRED_TO_THREE_THOUSAND_MILLI_SECONDS;
    public static final TEN_SECONDS_AND_ABOVE TWENTY_FOUR_TO_TWENTY_SIX_HUNDRED_MILLI_SECONDS;
    public static final TEN_SECONDS_AND_ABOVE TWENTY_SIX_TO_TWENTY_EIGHT_HUNDRED_MILLI_SECONDS;
    public static final TEN_SECONDS_AND_ABOVE TWENTY_TWO_TO_TWENTY_FOUR_HUNDRED_MILLI_SECONDS;
    public static final TEN_SECONDS_AND_ABOVE TWO_THOUSAND_TO_TWENTY_TWO_HUNDRED_MILLI_SECONDS;
    public static final TEN_SECONDS_AND_ABOVE TWO_TO_FOUR_HUNDRED_MILLI_SECOND;
    public static final TEN_SECONDS_AND_ABOVE ZERO_TO_FIFTY_MILLI_SECOND;
    private final long maxTime;
    private final long minTime;
    private final String timeSpent;

    public static String lookup(long l)
    {
        return LocalyticsBuckets.access$000(values(), l);
    }

    public static values valueOf(String s)
    {
        return (values)Enum.valueOf(com/weather/commons/analytics/LocalyticsBuckets$TimeSpentInMilliSeconds, s);
    }

    public static values[] values()
    {
        return (values[])$VALUES.clone();
    }

    public boolean contains(long l)
    {
        return l >= minTime && l <= maxTime;
    }

    public String getBucketString()
    {
        return timeSpent;
    }

    static 
    {
        ZERO_TO_FIFTY_MILLI_SECOND = new <init>("ZERO_TO_FIFTY_MILLI_SECOND", 0, "50 milli sec", 0x8000000000000000L, 50L);
        FIFTY_TO_ONE_HUNDRED_MILLI_SECOND = new <init>("FIFTY_TO_ONE_HUNDRED_MILLI_SECOND", 1, "51-100 milli sec", 51L, 100L);
        ONE_TO_TWO_HUNDRED_MILLI_SECOND = new <init>("ONE_TO_TWO_HUNDRED_MILLI_SECOND", 2, "101-200 milli sec", 101L, 200L);
        TWO_TO_FOUR_HUNDRED_MILLI_SECOND = new <init>("TWO_TO_FOUR_HUNDRED_MILLI_SECOND", 3, "201-400 milli sec", 201L, 400L);
        FOUR_TO_SIX_HUNDRED_MILLI_SECONDS = new <init>("FOUR_TO_SIX_HUNDRED_MILLI_SECONDS", 4, "401-600 milli  sec", 401L, 600L);
        SIX_TO_EIGHT_HUNDRED_MILLI_SECONDS = new <init>("SIX_TO_EIGHT_HUNDRED_MILLI_SECONDS", 5, "601-800 milli sec", 601L, 800L);
        EIGHT_HUNDRED_TO_THOUSAND_MILLI_SECONDS = new <init>("EIGHT_HUNDRED_TO_THOUSAND_MILLI_SECONDS", 6, "801-1000 milli sec", 801L, 1000L);
        ONE_THOUSAND_TO_TWELEVE_HUNDRED_MILLI_SECONDS = new <init>("ONE_THOUSAND_TO_TWELEVE_HUNDRED_MILLI_SECONDS", 7, "1001-1200 milli sec", 1001L, 1200L);
        TWELVE_HUNDRED_TO_FOURTEEN_HUNDRED_MILLI_SECONDS = new <init>("TWELVE_HUNDRED_TO_FOURTEEN_HUNDRED_MILLI_SECONDS", 8, "1201-1400 milli sec", 1201L, 1400L);
        FOURTEEN_TO_SIXTEEN_HUNDRED_MILLI_SECONDS = new <init>("FOURTEEN_TO_SIXTEEN_HUNDRED_MILLI_SECONDS", 9, "1401-1600 milli sec", 1401L, 1600L);
        SIXTEEN_TO_EIGHTEEN_HUNDRED_MILLI_SECONDS = new <init>("SIXTEEN_TO_EIGHTEEN_HUNDRED_MILLI_SECONDS", 10, "1601-1800 milli sec", 1601L, 1800L);
        EIGHTEEN_HUNDRED_TO_TWO_THOUSAND_MILLI_SECONDS = new <init>("EIGHTEEN_HUNDRED_TO_TWO_THOUSAND_MILLI_SECONDS", 11, "1801-2000 milli sec", 1801L, 2000L);
        TWO_THOUSAND_TO_TWENTY_TWO_HUNDRED_MILLI_SECONDS = new <init>("TWO_THOUSAND_TO_TWENTY_TWO_HUNDRED_MILLI_SECONDS", 12, "2001-2200 milli sec", 2001L, 2200L);
        TWENTY_TWO_TO_TWENTY_FOUR_HUNDRED_MILLI_SECONDS = new <init>("TWENTY_TWO_TO_TWENTY_FOUR_HUNDRED_MILLI_SECONDS", 13, "2201-2400 milli sec", 2201L, 2400L);
        TWENTY_FOUR_TO_TWENTY_SIX_HUNDRED_MILLI_SECONDS = new <init>("TWENTY_FOUR_TO_TWENTY_SIX_HUNDRED_MILLI_SECONDS", 14, "2401-2600 milli sec", 2401L, 2600L);
        TWENTY_SIX_TO_TWENTY_EIGHT_HUNDRED_MILLI_SECONDS = new <init>("TWENTY_SIX_TO_TWENTY_EIGHT_HUNDRED_MILLI_SECONDS", 15, "2601-2800 milli sec", 2601L, 2800L);
        TWENTY_EIGHT_HUNDRED_TO_THREE_THOUSAND_MILLI_SECONDS = new <init>("TWENTY_EIGHT_HUNDRED_TO_THREE_THOUSAND_MILLI_SECONDS", 16, "2801-3000 milli sec", 2801L, 3000L);
        THREE_THOUSAND_TO_THIRTY_TWO_HUNDRED_MILLI_SECONDS = new <init>("THREE_THOUSAND_TO_THIRTY_TWO_HUNDRED_MILLI_SECONDS", 17, "3001-3200 milli sec", 3001L, 3200L);
        THIRTY_TWO_TO_THIRTY_FOUR_HUNDRED_MILLI_SECONDS = new <init>("THIRTY_TWO_TO_THIRTY_FOUR_HUNDRED_MILLI_SECONDS", 18, "3201-3400 milli sec", 3201L, 3400L);
        THIRTY_FOUR_TO_THIRTY_SIX_HUNDRED_MILLI_SECONDS = new <init>("THIRTY_FOUR_TO_THIRTY_SIX_HUNDRED_MILLI_SECONDS", 19, "3401-3600 milli sec", 3401L, 3600L);
        THIRTY_SIX_TO_THIRTY_EIGHT_HUNDRED_MILLI_SECONDS = new <init>("THIRTY_SIX_TO_THIRTY_EIGHT_HUNDRED_MILLI_SECONDS", 20, "3601-3800 milli sec", 3601L, 3800L);
        THIRTY_EIGHT_HUNDRED_MILLI_SECONDS_TO_FOUR_SECONDS = new <init>("THIRTY_EIGHT_HUNDRED_MILLI_SECONDS_TO_FOUR_SECONDS", 21, "3801 milli sec to 4 sec", 3801L, 4000L);
        FOUR_SECONDS_TO_TEN_SECONDS = new <init>("FOUR_SECONDS_TO_TEN_SECONDS", 22, "4 sec to 10 sec", 4001L, 10000L);
        TEN_SECONDS_AND_ABOVE = new <init>("TEN_SECONDS_AND_ABOVE", 23, "above 10 sec", 10001L, 0x7fffffffffffffffL);
        $VALUES = (new .VALUES[] {
            ZERO_TO_FIFTY_MILLI_SECOND, FIFTY_TO_ONE_HUNDRED_MILLI_SECOND, ONE_TO_TWO_HUNDRED_MILLI_SECOND, TWO_TO_FOUR_HUNDRED_MILLI_SECOND, FOUR_TO_SIX_HUNDRED_MILLI_SECONDS, SIX_TO_EIGHT_HUNDRED_MILLI_SECONDS, EIGHT_HUNDRED_TO_THOUSAND_MILLI_SECONDS, ONE_THOUSAND_TO_TWELEVE_HUNDRED_MILLI_SECONDS, TWELVE_HUNDRED_TO_FOURTEEN_HUNDRED_MILLI_SECONDS, FOURTEEN_TO_SIXTEEN_HUNDRED_MILLI_SECONDS, 
            SIXTEEN_TO_EIGHTEEN_HUNDRED_MILLI_SECONDS, EIGHTEEN_HUNDRED_TO_TWO_THOUSAND_MILLI_SECONDS, TWO_THOUSAND_TO_TWENTY_TWO_HUNDRED_MILLI_SECONDS, TWENTY_TWO_TO_TWENTY_FOUR_HUNDRED_MILLI_SECONDS, TWENTY_FOUR_TO_TWENTY_SIX_HUNDRED_MILLI_SECONDS, TWENTY_SIX_TO_TWENTY_EIGHT_HUNDRED_MILLI_SECONDS, TWENTY_EIGHT_HUNDRED_TO_THREE_THOUSAND_MILLI_SECONDS, THREE_THOUSAND_TO_THIRTY_TWO_HUNDRED_MILLI_SECONDS, THIRTY_TWO_TO_THIRTY_FOUR_HUNDRED_MILLI_SECONDS, THIRTY_FOUR_TO_THIRTY_SIX_HUNDRED_MILLI_SECONDS, 
            THIRTY_SIX_TO_THIRTY_EIGHT_HUNDRED_MILLI_SECONDS, THIRTY_EIGHT_HUNDRED_MILLI_SECONDS_TO_FOUR_SECONDS, FOUR_SECONDS_TO_TEN_SECONDS, TEN_SECONDS_AND_ABOVE
        });
    }

    private (String s, int i, String s1, long l, long l1)
    {
        super(s, i);
        timeSpent = s1;
        minTime = l;
        maxTime = l1;
    }
}
